#
# Arm SCP/MCP Software
# Copyright (c) 2017-2020, Arm Limited and Contributors. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

BS_LIB_NAME := SCMI Power Domain Protocol
BS_LIB_SOURCES := mod_scmi_power_domain.c

include $(BS_DIR)/lib.mk
