#
# Renesas SCP/MCP Software
# Copyright (c) 2020-2021, Renesas Electronics Corporation. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

BS_LIB_NAME := RCAR SYSTEM
BS_LIB_SOURCES = mod_rcar_system.c \
                 rcar_common.c \
                 rcar_iic_dvfs.c \
                 rcar_pwc.c \
                 rcar_call_sram.S \
                 FreeRTOS_tick_config.c

include $(BS_DIR)/lib.mk
