/*
 * Arm SCP/MCP Software
 * Copyright (c) 2015-2020, Arm Limited and Contributors. All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef FWK_INTERNAL_SINGLE_THREAD_H
#define FWK_INTERNAL_SINGLE_THREAD_H

#include <fwk_event.h>
#include <fwk_list.h>

#include <stdbool.h>

/*
 * Thread component context. Exposed for testing purposes only.
 */

struct __fwk_thread_ctx {
    /* Thread framework component initialization completed flag */
    bool initialized;

    /*
     * Counter used to generate event cookies.
     */
    uint32_t event_cookie_counter;

    /*
     * Queue of event structures that are free to be filled in and linked
     * to the event queue or the ISR event queue.
     */
    struct fwk_slist free_event_queue;

    /* Queue of events, generated by ISRs, that are awaiting processing */
    struct fwk_slist isr_event_queue;

    /* Queue of events that are awaiting processing */
    struct fwk_slist event_queue;

    /* The event currently being processed */
    struct fwk_event *current_event;

    /* Event being processed when put_event_and_wait was called */
    struct fwk_event *previous_event;

    /*
     * Flag indicating the thread is waiting for the completion of the
     * processing of an event (true) or not (false). The thread
     * enters this waiting state when calling the fwk_thread_put_and_wait()
     * framework API requesting that the execution does not resume at the
     * caller until this event processing is complete and the response
     * received. The thread leaves this waiting state when the processing
     * of the aforementioned event is completed. The execution of the
     * caller is then resumed immediately: no other event processing occurs
     * between the end of the event processing and the caller execution being
     * resumed.
     *
     * Note that nested put_event_and_wait calls are not supported.
     */
    bool waiting_event_processing_completion;

    /*
     * The cookie of the event we are waiting for
     */
    uint32_t cookie;
};

/*
 * \brief Get thread component context.
 *
 * \note Only for testing.
 */
struct __fwk_thread_ctx *__fwk_thread_get_ctx(void);

#endif /* FWK_INTERNAL_SINGLE_THREAD_H */
