/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKFWK_TIME_H
#define _MOCKFWK_TIME_H

#include "unity.h"
#include "fwk_time.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void Mockfwk_time_Init(void);
void Mockfwk_time_Destroy(void);
void Mockfwk_time_Verify(void);




#define fwk_time_current_ExpectAndReturn(cmock_retval) fwk_time_current_CMockExpectAndReturn(__LINE__, cmock_retval)
void fwk_time_current_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, fwk_timestamp_t cmock_to_return);
#define fwk_time_stamp_duration_ExpectAnyArgsAndReturn(cmock_retval) fwk_time_stamp_duration_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void fwk_time_stamp_duration_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, fwk_duration_ns_t cmock_to_return);
#define fwk_time_stamp_duration_ExpectAndReturn(timestamp, cmock_retval) fwk_time_stamp_duration_CMockExpectAndReturn(__LINE__, timestamp, cmock_retval)
void fwk_time_stamp_duration_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, fwk_timestamp_t timestamp, fwk_duration_ns_t cmock_to_return);
#define fwk_time_duration_ExpectAnyArgsAndReturn(cmock_retval) fwk_time_duration_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void fwk_time_duration_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, fwk_duration_ns_t cmock_to_return);
#define fwk_time_duration_ExpectAndReturn(start, end, cmock_retval) fwk_time_duration_CMockExpectAndReturn(__LINE__, start, end, cmock_retval)
void fwk_time_duration_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, fwk_timestamp_t start, fwk_timestamp_t end, fwk_duration_ns_t cmock_to_return);
#define fwk_time_duration_us_ExpectAnyArgsAndReturn(cmock_retval) fwk_time_duration_us_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void fwk_time_duration_us_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, fwk_duration_us_t cmock_to_return);
#define fwk_time_duration_us_ExpectAndReturn(duration, cmock_retval) fwk_time_duration_us_CMockExpectAndReturn(__LINE__, duration, cmock_retval)
void fwk_time_duration_us_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, fwk_duration_ns_t duration, fwk_duration_us_t cmock_to_return);
#define fwk_time_duration_ms_ExpectAnyArgsAndReturn(cmock_retval) fwk_time_duration_ms_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void fwk_time_duration_ms_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, fwk_duration_ms_t cmock_to_return);
#define fwk_time_duration_ms_ExpectAndReturn(duration, cmock_retval) fwk_time_duration_ms_CMockExpectAndReturn(__LINE__, duration, cmock_retval)
void fwk_time_duration_ms_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, fwk_duration_ns_t duration, fwk_duration_ms_t cmock_to_return);
#define fwk_time_duration_s_ExpectAnyArgsAndReturn(cmock_retval) fwk_time_duration_s_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void fwk_time_duration_s_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, fwk_duration_s_t cmock_to_return);
#define fwk_time_duration_s_ExpectAndReturn(duration, cmock_retval) fwk_time_duration_s_CMockExpectAndReturn(__LINE__, duration, cmock_retval)
void fwk_time_duration_s_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, fwk_duration_ns_t duration, fwk_duration_s_t cmock_to_return);
#define fwk_time_duration_m_ExpectAnyArgsAndReturn(cmock_retval) fwk_time_duration_m_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void fwk_time_duration_m_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, fwk_duration_m_t cmock_to_return);
#define fwk_time_duration_m_ExpectAndReturn(duration, cmock_retval) fwk_time_duration_m_CMockExpectAndReturn(__LINE__, duration, cmock_retval)
void fwk_time_duration_m_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, fwk_duration_ns_t duration, fwk_duration_m_t cmock_to_return);
#define fwk_time_duration_h_ExpectAnyArgsAndReturn(cmock_retval) fwk_time_duration_h_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void fwk_time_duration_h_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, fwk_duration_h_t cmock_to_return);
#define fwk_time_duration_h_ExpectAndReturn(duration, cmock_retval) fwk_time_duration_h_CMockExpectAndReturn(__LINE__, duration, cmock_retval)
void fwk_time_duration_h_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, fwk_duration_ns_t duration, fwk_duration_h_t cmock_to_return);
#define fmw_time_driver_ExpectAnyArgsAndReturn(cmock_retval) fmw_time_driver_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void fmw_time_driver_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, struct fwk_time_driver cmock_to_return);
#define fmw_time_driver_ExpectAndReturn(ctx, cmock_retval) fmw_time_driver_CMockExpectAndReturn(__LINE__, ctx, cmock_retval)
void fmw_time_driver_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const void** ctx, struct fwk_time_driver cmock_to_return);

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
