/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mockfwk_id.h"

static const char* CMockString_api_id = "api_id";
static const char* CMockString_api_idx = "api_idx";
static const char* CMockString_element_id = "element_id";
static const char* CMockString_element_idx = "element_idx";
static const char* CMockString_event_id = "event_id";
static const char* CMockString_fwk_id_build_api_id = "fwk_id_build_api_id";
static const char* CMockString_fwk_id_build_element_id = "fwk_id_build_element_id";
static const char* CMockString_fwk_id_build_module_id = "fwk_id_build_module_id";
static const char* CMockString_fwk_id_build_sub_element_id = "fwk_id_build_sub_element_id";
static const char* CMockString_fwk_id_get_api_idx = "fwk_id_get_api_idx";
static const char* CMockString_fwk_id_get_element_idx = "fwk_id_get_element_idx";
static const char* CMockString_fwk_id_get_event_idx = "fwk_id_get_event_idx";
static const char* CMockString_fwk_id_get_module_idx = "fwk_id_get_module_idx";
static const char* CMockString_fwk_id_get_notification_idx = "fwk_id_get_notification_idx";
static const char* CMockString_fwk_id_get_sub_element_idx = "fwk_id_get_sub_element_idx";
static const char* CMockString_fwk_id_get_type = "fwk_id_get_type";
static const char* CMockString_fwk_id_is_equal = "fwk_id_is_equal";
static const char* CMockString_fwk_id_is_type = "fwk_id_is_type";
static const char* CMockString_fwk_id_type_is_valid = "fwk_id_type_is_valid";
static const char* CMockString_fwk_id_verbose_str = "fwk_id_verbose_str";
static const char* CMockString_fwk_optional_id_is_defined = "fwk_optional_id_is_defined";
static const char* CMockString_id = "id";
static const char* CMockString_left = "left";
static const char* CMockString_notification_id = "notification_id";
static const char* CMockString_right = "right";
static const char* CMockString_sub_element_id = "sub_element_id";
static const char* CMockString_sub_element_idx = "sub_element_idx";
static const char* CMockString_type = "type";

typedef struct _CMOCK_fwk_id_type_is_valid_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  bool ReturnVal;
  fwk_id_t Expected_id;

} CMOCK_fwk_id_type_is_valid_CALL_INSTANCE;

typedef struct _CMOCK_fwk_id_is_type_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  bool ReturnVal;
  fwk_id_t Expected_id;
  enum fwk_id_type Expected_type;

} CMOCK_fwk_id_is_type_CALL_INSTANCE;

typedef struct _CMOCK_fwk_id_get_type_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  enum fwk_id_type ReturnVal;
  fwk_id_t Expected_id;

} CMOCK_fwk_id_get_type_CALL_INSTANCE;

typedef struct _CMOCK_fwk_id_is_equal_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  bool ReturnVal;
  fwk_id_t Expected_left;
  fwk_id_t Expected_right;

} CMOCK_fwk_id_is_equal_CALL_INSTANCE;

typedef struct _CMOCK_fwk_optional_id_is_defined_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  bool ReturnVal;
  fwk_optional_id_t Expected_id;

} CMOCK_fwk_optional_id_is_defined_CALL_INSTANCE;

typedef struct _CMOCK_fwk_id_build_module_id_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  fwk_id_t ReturnVal;
  fwk_id_t Expected_id;

} CMOCK_fwk_id_build_module_id_CALL_INSTANCE;

typedef struct _CMOCK_fwk_id_build_element_id_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  fwk_id_t ReturnVal;
  fwk_id_t Expected_id;
  unsigned int Expected_element_idx;

} CMOCK_fwk_id_build_element_id_CALL_INSTANCE;

typedef struct _CMOCK_fwk_id_build_sub_element_id_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  fwk_id_t ReturnVal;
  fwk_id_t Expected_id;
  unsigned int Expected_sub_element_idx;

} CMOCK_fwk_id_build_sub_element_id_CALL_INSTANCE;

typedef struct _CMOCK_fwk_id_build_api_id_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  fwk_id_t ReturnVal;
  fwk_id_t Expected_id;
  unsigned int Expected_api_idx;

} CMOCK_fwk_id_build_api_id_CALL_INSTANCE;

typedef struct _CMOCK_fwk_id_get_module_idx_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  unsigned int ReturnVal;
  fwk_id_t Expected_id;

} CMOCK_fwk_id_get_module_idx_CALL_INSTANCE;

typedef struct _CMOCK_fwk_id_get_element_idx_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  unsigned int ReturnVal;
  fwk_id_t Expected_element_id;

} CMOCK_fwk_id_get_element_idx_CALL_INSTANCE;

typedef struct _CMOCK_fwk_id_get_sub_element_idx_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  unsigned int ReturnVal;
  fwk_id_t Expected_sub_element_id;

} CMOCK_fwk_id_get_sub_element_idx_CALL_INSTANCE;

typedef struct _CMOCK_fwk_id_get_api_idx_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  unsigned int ReturnVal;
  fwk_id_t Expected_api_id;

} CMOCK_fwk_id_get_api_idx_CALL_INSTANCE;

typedef struct _CMOCK_fwk_id_get_event_idx_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  unsigned int ReturnVal;
  fwk_id_t Expected_event_id;

} CMOCK_fwk_id_get_event_idx_CALL_INSTANCE;

typedef struct _CMOCK_fwk_id_get_notification_idx_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  unsigned int ReturnVal;
  fwk_id_t Expected_notification_id;

} CMOCK_fwk_id_get_notification_idx_CALL_INSTANCE;

typedef struct _CMOCK_fwk_id_verbose_str_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  struct fwk_id_verbose_fmt ReturnVal;
  fwk_id_t Expected_id;

} CMOCK_fwk_id_verbose_str_CALL_INSTANCE;

static struct Mockfwk_idInstance
{
  CMOCK_MEM_INDEX_TYPE fwk_id_type_is_valid_CallInstance;
  CMOCK_MEM_INDEX_TYPE fwk_id_is_type_CallInstance;
  CMOCK_MEM_INDEX_TYPE fwk_id_get_type_CallInstance;
  CMOCK_MEM_INDEX_TYPE fwk_id_is_equal_CallInstance;
  CMOCK_MEM_INDEX_TYPE fwk_optional_id_is_defined_CallInstance;
  CMOCK_MEM_INDEX_TYPE fwk_id_build_module_id_CallInstance;
  CMOCK_MEM_INDEX_TYPE fwk_id_build_element_id_CallInstance;
  CMOCK_MEM_INDEX_TYPE fwk_id_build_sub_element_id_CallInstance;
  CMOCK_MEM_INDEX_TYPE fwk_id_build_api_id_CallInstance;
  CMOCK_MEM_INDEX_TYPE fwk_id_get_module_idx_CallInstance;
  CMOCK_MEM_INDEX_TYPE fwk_id_get_element_idx_CallInstance;
  CMOCK_MEM_INDEX_TYPE fwk_id_get_sub_element_idx_CallInstance;
  CMOCK_MEM_INDEX_TYPE fwk_id_get_api_idx_CallInstance;
  CMOCK_MEM_INDEX_TYPE fwk_id_get_event_idx_CallInstance;
  CMOCK_MEM_INDEX_TYPE fwk_id_get_notification_idx_CallInstance;
  CMOCK_MEM_INDEX_TYPE fwk_id_verbose_str_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockfwk_id_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.fwk_id_type_is_valid_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_fwk_id_type_is_valid);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.fwk_id_is_type_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_fwk_id_is_type);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.fwk_id_get_type_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_fwk_id_get_type);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.fwk_id_is_equal_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_fwk_id_is_equal);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.fwk_optional_id_is_defined_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_fwk_optional_id_is_defined);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.fwk_id_build_module_id_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_fwk_id_build_module_id);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.fwk_id_build_element_id_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_fwk_id_build_element_id);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.fwk_id_build_sub_element_id_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_fwk_id_build_sub_element_id);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.fwk_id_build_api_id_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_fwk_id_build_api_id);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.fwk_id_get_module_idx_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_fwk_id_get_module_idx);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.fwk_id_get_element_idx_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_fwk_id_get_element_idx);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.fwk_id_get_sub_element_idx_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_fwk_id_get_sub_element_idx);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.fwk_id_get_api_idx_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_fwk_id_get_api_idx);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.fwk_id_get_event_idx_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_fwk_id_get_event_idx);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.fwk_id_get_notification_idx_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_fwk_id_get_notification_idx);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.fwk_id_verbose_str_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_fwk_id_verbose_str);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
}

void Mockfwk_id_Init(void)
{
  Mockfwk_id_Destroy();
}

void Mockfwk_id_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

bool fwk_id_type_is_valid(fwk_id_t id)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_fwk_id_type_is_valid_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_fwk_id_type_is_valid);
  cmock_call_instance = (CMOCK_fwk_id_type_is_valid_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.fwk_id_type_is_valid_CallInstance);
  Mock.fwk_id_type_is_valid_CallInstance = CMock_Guts_MemNext(Mock.fwk_id_type_is_valid_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  {
    UNITY_SET_DETAILS(CMockString_fwk_id_type_is_valid,CMockString_id);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_id), (void*)(&id), sizeof(fwk_id_t), cmock_line, CMockStringMismatch);
  }
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_fwk_id_type_is_valid(CMOCK_fwk_id_type_is_valid_CALL_INSTANCE* cmock_call_instance, fwk_id_t id);
void CMockExpectParameters_fwk_id_type_is_valid(CMOCK_fwk_id_type_is_valid_CALL_INSTANCE* cmock_call_instance, fwk_id_t id)
{
  memcpy((void*)(&cmock_call_instance->Expected_id), (void*)(&id),
         sizeof(fwk_id_t[sizeof(id) == sizeof(fwk_id_t) ? 1 : -1])); /* add fwk_id_t to :treat_as_array if this causes an error */
}

void fwk_id_type_is_valid_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_fwk_id_type_is_valid_CALL_INSTANCE));
  CMOCK_fwk_id_type_is_valid_CALL_INSTANCE* cmock_call_instance = (CMOCK_fwk_id_type_is_valid_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.fwk_id_type_is_valid_CallInstance = CMock_Guts_MemChain(Mock.fwk_id_type_is_valid_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void fwk_id_type_is_valid_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, fwk_id_t id, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_fwk_id_type_is_valid_CALL_INSTANCE));
  CMOCK_fwk_id_type_is_valid_CALL_INSTANCE* cmock_call_instance = (CMOCK_fwk_id_type_is_valid_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.fwk_id_type_is_valid_CallInstance = CMock_Guts_MemChain(Mock.fwk_id_type_is_valid_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_fwk_id_type_is_valid(cmock_call_instance, id);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

bool fwk_id_is_type(fwk_id_t id, enum fwk_id_type type)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_fwk_id_is_type_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_fwk_id_is_type);
  cmock_call_instance = (CMOCK_fwk_id_is_type_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.fwk_id_is_type_CallInstance);
  Mock.fwk_id_is_type_CallInstance = CMock_Guts_MemNext(Mock.fwk_id_is_type_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  {
    UNITY_SET_DETAILS(CMockString_fwk_id_is_type,CMockString_id);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_id), (void*)(&id), sizeof(fwk_id_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_fwk_id_is_type,CMockString_type);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_type), (void*)(&type), sizeof(enum fwk_id_type), cmock_line, CMockStringMismatch);
  }
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_fwk_id_is_type(CMOCK_fwk_id_is_type_CALL_INSTANCE* cmock_call_instance, fwk_id_t id, enum fwk_id_type type);
void CMockExpectParameters_fwk_id_is_type(CMOCK_fwk_id_is_type_CALL_INSTANCE* cmock_call_instance, fwk_id_t id, enum fwk_id_type type)
{
  memcpy((void*)(&cmock_call_instance->Expected_id), (void*)(&id),
         sizeof(fwk_id_t[sizeof(id) == sizeof(fwk_id_t) ? 1 : -1])); /* add fwk_id_t to :treat_as_array if this causes an error */
  memcpy((void*)(&cmock_call_instance->Expected_type), (void*)(&type),
         sizeof(enum fwk_id_type[sizeof(type) == sizeof(enum fwk_id_type) ? 1 : -1])); /* add enum fwk_id_type to :treat_as_array if this causes an error */
}

void fwk_id_is_type_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_fwk_id_is_type_CALL_INSTANCE));
  CMOCK_fwk_id_is_type_CALL_INSTANCE* cmock_call_instance = (CMOCK_fwk_id_is_type_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.fwk_id_is_type_CallInstance = CMock_Guts_MemChain(Mock.fwk_id_is_type_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void fwk_id_is_type_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, fwk_id_t id, enum fwk_id_type type, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_fwk_id_is_type_CALL_INSTANCE));
  CMOCK_fwk_id_is_type_CALL_INSTANCE* cmock_call_instance = (CMOCK_fwk_id_is_type_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.fwk_id_is_type_CallInstance = CMock_Guts_MemChain(Mock.fwk_id_is_type_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_fwk_id_is_type(cmock_call_instance, id, type);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

enum fwk_id_type fwk_id_get_type(fwk_id_t id)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_fwk_id_get_type_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_fwk_id_get_type);
  cmock_call_instance = (CMOCK_fwk_id_get_type_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.fwk_id_get_type_CallInstance);
  Mock.fwk_id_get_type_CallInstance = CMock_Guts_MemNext(Mock.fwk_id_get_type_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  {
    UNITY_SET_DETAILS(CMockString_fwk_id_get_type,CMockString_id);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_id), (void*)(&id), sizeof(fwk_id_t), cmock_line, CMockStringMismatch);
  }
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_fwk_id_get_type(CMOCK_fwk_id_get_type_CALL_INSTANCE* cmock_call_instance, fwk_id_t id);
void CMockExpectParameters_fwk_id_get_type(CMOCK_fwk_id_get_type_CALL_INSTANCE* cmock_call_instance, fwk_id_t id)
{
  memcpy((void*)(&cmock_call_instance->Expected_id), (void*)(&id),
         sizeof(fwk_id_t[sizeof(id) == sizeof(fwk_id_t) ? 1 : -1])); /* add fwk_id_t to :treat_as_array if this causes an error */
}

void fwk_id_get_type_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, enum fwk_id_type cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_fwk_id_get_type_CALL_INSTANCE));
  CMOCK_fwk_id_get_type_CALL_INSTANCE* cmock_call_instance = (CMOCK_fwk_id_get_type_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.fwk_id_get_type_CallInstance = CMock_Guts_MemChain(Mock.fwk_id_get_type_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void fwk_id_get_type_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, fwk_id_t id, enum fwk_id_type cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_fwk_id_get_type_CALL_INSTANCE));
  CMOCK_fwk_id_get_type_CALL_INSTANCE* cmock_call_instance = (CMOCK_fwk_id_get_type_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.fwk_id_get_type_CallInstance = CMock_Guts_MemChain(Mock.fwk_id_get_type_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_fwk_id_get_type(cmock_call_instance, id);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(enum fwk_id_type[sizeof(cmock_to_return) == sizeof(enum fwk_id_type) ? 1 : -1])); /* add enum fwk_id_type to :treat_as_array if this causes an error */
}

bool fwk_id_is_equal(fwk_id_t left, fwk_id_t right)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_fwk_id_is_equal_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_fwk_id_is_equal);
  cmock_call_instance = (CMOCK_fwk_id_is_equal_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.fwk_id_is_equal_CallInstance);
  Mock.fwk_id_is_equal_CallInstance = CMock_Guts_MemNext(Mock.fwk_id_is_equal_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  {
    UNITY_SET_DETAILS(CMockString_fwk_id_is_equal,CMockString_left);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_left), (void*)(&left), sizeof(fwk_id_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_fwk_id_is_equal,CMockString_right);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_right), (void*)(&right), sizeof(fwk_id_t), cmock_line, CMockStringMismatch);
  }
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_fwk_id_is_equal(CMOCK_fwk_id_is_equal_CALL_INSTANCE* cmock_call_instance, fwk_id_t left, fwk_id_t right);
void CMockExpectParameters_fwk_id_is_equal(CMOCK_fwk_id_is_equal_CALL_INSTANCE* cmock_call_instance, fwk_id_t left, fwk_id_t right)
{
  memcpy((void*)(&cmock_call_instance->Expected_left), (void*)(&left),
         sizeof(fwk_id_t[sizeof(left) == sizeof(fwk_id_t) ? 1 : -1])); /* add fwk_id_t to :treat_as_array if this causes an error */
  memcpy((void*)(&cmock_call_instance->Expected_right), (void*)(&right),
         sizeof(fwk_id_t[sizeof(right) == sizeof(fwk_id_t) ? 1 : -1])); /* add fwk_id_t to :treat_as_array if this causes an error */
}

void fwk_id_is_equal_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_fwk_id_is_equal_CALL_INSTANCE));
  CMOCK_fwk_id_is_equal_CALL_INSTANCE* cmock_call_instance = (CMOCK_fwk_id_is_equal_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.fwk_id_is_equal_CallInstance = CMock_Guts_MemChain(Mock.fwk_id_is_equal_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void fwk_id_is_equal_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, fwk_id_t left, fwk_id_t right, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_fwk_id_is_equal_CALL_INSTANCE));
  CMOCK_fwk_id_is_equal_CALL_INSTANCE* cmock_call_instance = (CMOCK_fwk_id_is_equal_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.fwk_id_is_equal_CallInstance = CMock_Guts_MemChain(Mock.fwk_id_is_equal_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_fwk_id_is_equal(cmock_call_instance, left, right);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

bool fwk_optional_id_is_defined(fwk_optional_id_t id)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_fwk_optional_id_is_defined_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_fwk_optional_id_is_defined);
  cmock_call_instance = (CMOCK_fwk_optional_id_is_defined_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.fwk_optional_id_is_defined_CallInstance);
  Mock.fwk_optional_id_is_defined_CallInstance = CMock_Guts_MemNext(Mock.fwk_optional_id_is_defined_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  {
    UNITY_SET_DETAILS(CMockString_fwk_optional_id_is_defined,CMockString_id);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_id), (void*)(&id), sizeof(fwk_optional_id_t), cmock_line, CMockStringMismatch);
  }
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_fwk_optional_id_is_defined(CMOCK_fwk_optional_id_is_defined_CALL_INSTANCE* cmock_call_instance, fwk_optional_id_t id);
void CMockExpectParameters_fwk_optional_id_is_defined(CMOCK_fwk_optional_id_is_defined_CALL_INSTANCE* cmock_call_instance, fwk_optional_id_t id)
{
  memcpy((void*)(&cmock_call_instance->Expected_id), (void*)(&id),
         sizeof(fwk_optional_id_t[sizeof(id) == sizeof(fwk_optional_id_t) ? 1 : -1])); /* add fwk_optional_id_t to :treat_as_array if this causes an error */
}

void fwk_optional_id_is_defined_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_fwk_optional_id_is_defined_CALL_INSTANCE));
  CMOCK_fwk_optional_id_is_defined_CALL_INSTANCE* cmock_call_instance = (CMOCK_fwk_optional_id_is_defined_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.fwk_optional_id_is_defined_CallInstance = CMock_Guts_MemChain(Mock.fwk_optional_id_is_defined_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void fwk_optional_id_is_defined_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, fwk_optional_id_t id, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_fwk_optional_id_is_defined_CALL_INSTANCE));
  CMOCK_fwk_optional_id_is_defined_CALL_INSTANCE* cmock_call_instance = (CMOCK_fwk_optional_id_is_defined_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.fwk_optional_id_is_defined_CallInstance = CMock_Guts_MemChain(Mock.fwk_optional_id_is_defined_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_fwk_optional_id_is_defined(cmock_call_instance, id);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

fwk_id_t fwk_id_build_module_id(fwk_id_t id)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_fwk_id_build_module_id_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_fwk_id_build_module_id);
  cmock_call_instance = (CMOCK_fwk_id_build_module_id_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.fwk_id_build_module_id_CallInstance);
  Mock.fwk_id_build_module_id_CallInstance = CMock_Guts_MemNext(Mock.fwk_id_build_module_id_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  {
    UNITY_SET_DETAILS(CMockString_fwk_id_build_module_id,CMockString_id);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_id), (void*)(&id), sizeof(fwk_id_t), cmock_line, CMockStringMismatch);
  }
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_fwk_id_build_module_id(CMOCK_fwk_id_build_module_id_CALL_INSTANCE* cmock_call_instance, fwk_id_t id);
void CMockExpectParameters_fwk_id_build_module_id(CMOCK_fwk_id_build_module_id_CALL_INSTANCE* cmock_call_instance, fwk_id_t id)
{
  memcpy((void*)(&cmock_call_instance->Expected_id), (void*)(&id),
         sizeof(fwk_id_t[sizeof(id) == sizeof(fwk_id_t) ? 1 : -1])); /* add fwk_id_t to :treat_as_array if this causes an error */
}

void fwk_id_build_module_id_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, fwk_id_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_fwk_id_build_module_id_CALL_INSTANCE));
  CMOCK_fwk_id_build_module_id_CALL_INSTANCE* cmock_call_instance = (CMOCK_fwk_id_build_module_id_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.fwk_id_build_module_id_CallInstance = CMock_Guts_MemChain(Mock.fwk_id_build_module_id_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void fwk_id_build_module_id_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, fwk_id_t id, fwk_id_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_fwk_id_build_module_id_CALL_INSTANCE));
  CMOCK_fwk_id_build_module_id_CALL_INSTANCE* cmock_call_instance = (CMOCK_fwk_id_build_module_id_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.fwk_id_build_module_id_CallInstance = CMock_Guts_MemChain(Mock.fwk_id_build_module_id_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_fwk_id_build_module_id(cmock_call_instance, id);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(fwk_id_t[sizeof(cmock_to_return) == sizeof(fwk_id_t) ? 1 : -1])); /* add fwk_id_t to :treat_as_array if this causes an error */
}

fwk_id_t fwk_id_build_element_id(fwk_id_t id, unsigned int element_idx)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_fwk_id_build_element_id_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_fwk_id_build_element_id);
  cmock_call_instance = (CMOCK_fwk_id_build_element_id_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.fwk_id_build_element_id_CallInstance);
  Mock.fwk_id_build_element_id_CallInstance = CMock_Guts_MemNext(Mock.fwk_id_build_element_id_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  {
    UNITY_SET_DETAILS(CMockString_fwk_id_build_element_id,CMockString_id);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_id), (void*)(&id), sizeof(fwk_id_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_fwk_id_build_element_id,CMockString_element_idx);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_element_idx, element_idx, cmock_line, CMockStringMismatch);
  }
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_fwk_id_build_element_id(CMOCK_fwk_id_build_element_id_CALL_INSTANCE* cmock_call_instance, fwk_id_t id, unsigned int element_idx);
void CMockExpectParameters_fwk_id_build_element_id(CMOCK_fwk_id_build_element_id_CALL_INSTANCE* cmock_call_instance, fwk_id_t id, unsigned int element_idx)
{
  memcpy((void*)(&cmock_call_instance->Expected_id), (void*)(&id),
         sizeof(fwk_id_t[sizeof(id) == sizeof(fwk_id_t) ? 1 : -1])); /* add fwk_id_t to :treat_as_array if this causes an error */
  cmock_call_instance->Expected_element_idx = element_idx;
}

void fwk_id_build_element_id_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, fwk_id_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_fwk_id_build_element_id_CALL_INSTANCE));
  CMOCK_fwk_id_build_element_id_CALL_INSTANCE* cmock_call_instance = (CMOCK_fwk_id_build_element_id_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.fwk_id_build_element_id_CallInstance = CMock_Guts_MemChain(Mock.fwk_id_build_element_id_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void fwk_id_build_element_id_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, fwk_id_t id, unsigned int element_idx, fwk_id_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_fwk_id_build_element_id_CALL_INSTANCE));
  CMOCK_fwk_id_build_element_id_CALL_INSTANCE* cmock_call_instance = (CMOCK_fwk_id_build_element_id_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.fwk_id_build_element_id_CallInstance = CMock_Guts_MemChain(Mock.fwk_id_build_element_id_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_fwk_id_build_element_id(cmock_call_instance, id, element_idx);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(fwk_id_t[sizeof(cmock_to_return) == sizeof(fwk_id_t) ? 1 : -1])); /* add fwk_id_t to :treat_as_array if this causes an error */
}

fwk_id_t fwk_id_build_sub_element_id(fwk_id_t id, unsigned int sub_element_idx)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_fwk_id_build_sub_element_id_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_fwk_id_build_sub_element_id);
  cmock_call_instance = (CMOCK_fwk_id_build_sub_element_id_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.fwk_id_build_sub_element_id_CallInstance);
  Mock.fwk_id_build_sub_element_id_CallInstance = CMock_Guts_MemNext(Mock.fwk_id_build_sub_element_id_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  {
    UNITY_SET_DETAILS(CMockString_fwk_id_build_sub_element_id,CMockString_id);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_id), (void*)(&id), sizeof(fwk_id_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_fwk_id_build_sub_element_id,CMockString_sub_element_idx);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_sub_element_idx, sub_element_idx, cmock_line, CMockStringMismatch);
  }
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_fwk_id_build_sub_element_id(CMOCK_fwk_id_build_sub_element_id_CALL_INSTANCE* cmock_call_instance, fwk_id_t id, unsigned int sub_element_idx);
void CMockExpectParameters_fwk_id_build_sub_element_id(CMOCK_fwk_id_build_sub_element_id_CALL_INSTANCE* cmock_call_instance, fwk_id_t id, unsigned int sub_element_idx)
{
  memcpy((void*)(&cmock_call_instance->Expected_id), (void*)(&id),
         sizeof(fwk_id_t[sizeof(id) == sizeof(fwk_id_t) ? 1 : -1])); /* add fwk_id_t to :treat_as_array if this causes an error */
  cmock_call_instance->Expected_sub_element_idx = sub_element_idx;
}

void fwk_id_build_sub_element_id_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, fwk_id_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_fwk_id_build_sub_element_id_CALL_INSTANCE));
  CMOCK_fwk_id_build_sub_element_id_CALL_INSTANCE* cmock_call_instance = (CMOCK_fwk_id_build_sub_element_id_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.fwk_id_build_sub_element_id_CallInstance = CMock_Guts_MemChain(Mock.fwk_id_build_sub_element_id_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void fwk_id_build_sub_element_id_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, fwk_id_t id, unsigned int sub_element_idx, fwk_id_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_fwk_id_build_sub_element_id_CALL_INSTANCE));
  CMOCK_fwk_id_build_sub_element_id_CALL_INSTANCE* cmock_call_instance = (CMOCK_fwk_id_build_sub_element_id_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.fwk_id_build_sub_element_id_CallInstance = CMock_Guts_MemChain(Mock.fwk_id_build_sub_element_id_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_fwk_id_build_sub_element_id(cmock_call_instance, id, sub_element_idx);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(fwk_id_t[sizeof(cmock_to_return) == sizeof(fwk_id_t) ? 1 : -1])); /* add fwk_id_t to :treat_as_array if this causes an error */
}

fwk_id_t fwk_id_build_api_id(fwk_id_t id, unsigned int api_idx)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_fwk_id_build_api_id_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_fwk_id_build_api_id);
  cmock_call_instance = (CMOCK_fwk_id_build_api_id_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.fwk_id_build_api_id_CallInstance);
  Mock.fwk_id_build_api_id_CallInstance = CMock_Guts_MemNext(Mock.fwk_id_build_api_id_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  {
    UNITY_SET_DETAILS(CMockString_fwk_id_build_api_id,CMockString_id);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_id), (void*)(&id), sizeof(fwk_id_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_fwk_id_build_api_id,CMockString_api_idx);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_api_idx, api_idx, cmock_line, CMockStringMismatch);
  }
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_fwk_id_build_api_id(CMOCK_fwk_id_build_api_id_CALL_INSTANCE* cmock_call_instance, fwk_id_t id, unsigned int api_idx);
void CMockExpectParameters_fwk_id_build_api_id(CMOCK_fwk_id_build_api_id_CALL_INSTANCE* cmock_call_instance, fwk_id_t id, unsigned int api_idx)
{
  memcpy((void*)(&cmock_call_instance->Expected_id), (void*)(&id),
         sizeof(fwk_id_t[sizeof(id) == sizeof(fwk_id_t) ? 1 : -1])); /* add fwk_id_t to :treat_as_array if this causes an error */
  cmock_call_instance->Expected_api_idx = api_idx;
}

void fwk_id_build_api_id_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, fwk_id_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_fwk_id_build_api_id_CALL_INSTANCE));
  CMOCK_fwk_id_build_api_id_CALL_INSTANCE* cmock_call_instance = (CMOCK_fwk_id_build_api_id_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.fwk_id_build_api_id_CallInstance = CMock_Guts_MemChain(Mock.fwk_id_build_api_id_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void fwk_id_build_api_id_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, fwk_id_t id, unsigned int api_idx, fwk_id_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_fwk_id_build_api_id_CALL_INSTANCE));
  CMOCK_fwk_id_build_api_id_CALL_INSTANCE* cmock_call_instance = (CMOCK_fwk_id_build_api_id_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.fwk_id_build_api_id_CallInstance = CMock_Guts_MemChain(Mock.fwk_id_build_api_id_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_fwk_id_build_api_id(cmock_call_instance, id, api_idx);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(fwk_id_t[sizeof(cmock_to_return) == sizeof(fwk_id_t) ? 1 : -1])); /* add fwk_id_t to :treat_as_array if this causes an error */
}

unsigned int fwk_id_get_module_idx(fwk_id_t id)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_fwk_id_get_module_idx_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_fwk_id_get_module_idx);
  cmock_call_instance = (CMOCK_fwk_id_get_module_idx_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.fwk_id_get_module_idx_CallInstance);
  Mock.fwk_id_get_module_idx_CallInstance = CMock_Guts_MemNext(Mock.fwk_id_get_module_idx_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  {
    UNITY_SET_DETAILS(CMockString_fwk_id_get_module_idx,CMockString_id);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_id), (void*)(&id), sizeof(fwk_id_t), cmock_line, CMockStringMismatch);
  }
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_fwk_id_get_module_idx(CMOCK_fwk_id_get_module_idx_CALL_INSTANCE* cmock_call_instance, fwk_id_t id);
void CMockExpectParameters_fwk_id_get_module_idx(CMOCK_fwk_id_get_module_idx_CALL_INSTANCE* cmock_call_instance, fwk_id_t id)
{
  memcpy((void*)(&cmock_call_instance->Expected_id), (void*)(&id),
         sizeof(fwk_id_t[sizeof(id) == sizeof(fwk_id_t) ? 1 : -1])); /* add fwk_id_t to :treat_as_array if this causes an error */
}

void fwk_id_get_module_idx_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, unsigned int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_fwk_id_get_module_idx_CALL_INSTANCE));
  CMOCK_fwk_id_get_module_idx_CALL_INSTANCE* cmock_call_instance = (CMOCK_fwk_id_get_module_idx_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.fwk_id_get_module_idx_CallInstance = CMock_Guts_MemChain(Mock.fwk_id_get_module_idx_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void fwk_id_get_module_idx_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, fwk_id_t id, unsigned int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_fwk_id_get_module_idx_CALL_INSTANCE));
  CMOCK_fwk_id_get_module_idx_CALL_INSTANCE* cmock_call_instance = (CMOCK_fwk_id_get_module_idx_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.fwk_id_get_module_idx_CallInstance = CMock_Guts_MemChain(Mock.fwk_id_get_module_idx_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_fwk_id_get_module_idx(cmock_call_instance, id);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

unsigned int fwk_id_get_element_idx(fwk_id_t element_id)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_fwk_id_get_element_idx_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_fwk_id_get_element_idx);
  cmock_call_instance = (CMOCK_fwk_id_get_element_idx_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.fwk_id_get_element_idx_CallInstance);
  Mock.fwk_id_get_element_idx_CallInstance = CMock_Guts_MemNext(Mock.fwk_id_get_element_idx_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  {
    UNITY_SET_DETAILS(CMockString_fwk_id_get_element_idx,CMockString_element_id);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_element_id), (void*)(&element_id), sizeof(fwk_id_t), cmock_line, CMockStringMismatch);
  }
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_fwk_id_get_element_idx(CMOCK_fwk_id_get_element_idx_CALL_INSTANCE* cmock_call_instance, fwk_id_t element_id);
void CMockExpectParameters_fwk_id_get_element_idx(CMOCK_fwk_id_get_element_idx_CALL_INSTANCE* cmock_call_instance, fwk_id_t element_id)
{
  memcpy((void*)(&cmock_call_instance->Expected_element_id), (void*)(&element_id),
         sizeof(fwk_id_t[sizeof(element_id) == sizeof(fwk_id_t) ? 1 : -1])); /* add fwk_id_t to :treat_as_array if this causes an error */
}

void fwk_id_get_element_idx_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, unsigned int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_fwk_id_get_element_idx_CALL_INSTANCE));
  CMOCK_fwk_id_get_element_idx_CALL_INSTANCE* cmock_call_instance = (CMOCK_fwk_id_get_element_idx_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.fwk_id_get_element_idx_CallInstance = CMock_Guts_MemChain(Mock.fwk_id_get_element_idx_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void fwk_id_get_element_idx_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, fwk_id_t element_id, unsigned int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_fwk_id_get_element_idx_CALL_INSTANCE));
  CMOCK_fwk_id_get_element_idx_CALL_INSTANCE* cmock_call_instance = (CMOCK_fwk_id_get_element_idx_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.fwk_id_get_element_idx_CallInstance = CMock_Guts_MemChain(Mock.fwk_id_get_element_idx_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_fwk_id_get_element_idx(cmock_call_instance, element_id);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

unsigned int fwk_id_get_sub_element_idx(fwk_id_t sub_element_id)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_fwk_id_get_sub_element_idx_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_fwk_id_get_sub_element_idx);
  cmock_call_instance = (CMOCK_fwk_id_get_sub_element_idx_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.fwk_id_get_sub_element_idx_CallInstance);
  Mock.fwk_id_get_sub_element_idx_CallInstance = CMock_Guts_MemNext(Mock.fwk_id_get_sub_element_idx_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  {
    UNITY_SET_DETAILS(CMockString_fwk_id_get_sub_element_idx,CMockString_sub_element_id);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_sub_element_id), (void*)(&sub_element_id), sizeof(fwk_id_t), cmock_line, CMockStringMismatch);
  }
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_fwk_id_get_sub_element_idx(CMOCK_fwk_id_get_sub_element_idx_CALL_INSTANCE* cmock_call_instance, fwk_id_t sub_element_id);
void CMockExpectParameters_fwk_id_get_sub_element_idx(CMOCK_fwk_id_get_sub_element_idx_CALL_INSTANCE* cmock_call_instance, fwk_id_t sub_element_id)
{
  memcpy((void*)(&cmock_call_instance->Expected_sub_element_id), (void*)(&sub_element_id),
         sizeof(fwk_id_t[sizeof(sub_element_id) == sizeof(fwk_id_t) ? 1 : -1])); /* add fwk_id_t to :treat_as_array if this causes an error */
}

void fwk_id_get_sub_element_idx_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, unsigned int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_fwk_id_get_sub_element_idx_CALL_INSTANCE));
  CMOCK_fwk_id_get_sub_element_idx_CALL_INSTANCE* cmock_call_instance = (CMOCK_fwk_id_get_sub_element_idx_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.fwk_id_get_sub_element_idx_CallInstance = CMock_Guts_MemChain(Mock.fwk_id_get_sub_element_idx_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void fwk_id_get_sub_element_idx_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, fwk_id_t sub_element_id, unsigned int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_fwk_id_get_sub_element_idx_CALL_INSTANCE));
  CMOCK_fwk_id_get_sub_element_idx_CALL_INSTANCE* cmock_call_instance = (CMOCK_fwk_id_get_sub_element_idx_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.fwk_id_get_sub_element_idx_CallInstance = CMock_Guts_MemChain(Mock.fwk_id_get_sub_element_idx_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_fwk_id_get_sub_element_idx(cmock_call_instance, sub_element_id);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

unsigned int fwk_id_get_api_idx(fwk_id_t api_id)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_fwk_id_get_api_idx_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_fwk_id_get_api_idx);
  cmock_call_instance = (CMOCK_fwk_id_get_api_idx_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.fwk_id_get_api_idx_CallInstance);
  Mock.fwk_id_get_api_idx_CallInstance = CMock_Guts_MemNext(Mock.fwk_id_get_api_idx_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  {
    UNITY_SET_DETAILS(CMockString_fwk_id_get_api_idx,CMockString_api_id);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_api_id), (void*)(&api_id), sizeof(fwk_id_t), cmock_line, CMockStringMismatch);
  }
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_fwk_id_get_api_idx(CMOCK_fwk_id_get_api_idx_CALL_INSTANCE* cmock_call_instance, fwk_id_t api_id);
void CMockExpectParameters_fwk_id_get_api_idx(CMOCK_fwk_id_get_api_idx_CALL_INSTANCE* cmock_call_instance, fwk_id_t api_id)
{
  memcpy((void*)(&cmock_call_instance->Expected_api_id), (void*)(&api_id),
         sizeof(fwk_id_t[sizeof(api_id) == sizeof(fwk_id_t) ? 1 : -1])); /* add fwk_id_t to :treat_as_array if this causes an error */
}

void fwk_id_get_api_idx_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, unsigned int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_fwk_id_get_api_idx_CALL_INSTANCE));
  CMOCK_fwk_id_get_api_idx_CALL_INSTANCE* cmock_call_instance = (CMOCK_fwk_id_get_api_idx_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.fwk_id_get_api_idx_CallInstance = CMock_Guts_MemChain(Mock.fwk_id_get_api_idx_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void fwk_id_get_api_idx_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, fwk_id_t api_id, unsigned int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_fwk_id_get_api_idx_CALL_INSTANCE));
  CMOCK_fwk_id_get_api_idx_CALL_INSTANCE* cmock_call_instance = (CMOCK_fwk_id_get_api_idx_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.fwk_id_get_api_idx_CallInstance = CMock_Guts_MemChain(Mock.fwk_id_get_api_idx_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_fwk_id_get_api_idx(cmock_call_instance, api_id);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

unsigned int fwk_id_get_event_idx(fwk_id_t event_id)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_fwk_id_get_event_idx_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_fwk_id_get_event_idx);
  cmock_call_instance = (CMOCK_fwk_id_get_event_idx_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.fwk_id_get_event_idx_CallInstance);
  Mock.fwk_id_get_event_idx_CallInstance = CMock_Guts_MemNext(Mock.fwk_id_get_event_idx_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  {
    UNITY_SET_DETAILS(CMockString_fwk_id_get_event_idx,CMockString_event_id);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_event_id), (void*)(&event_id), sizeof(fwk_id_t), cmock_line, CMockStringMismatch);
  }
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_fwk_id_get_event_idx(CMOCK_fwk_id_get_event_idx_CALL_INSTANCE* cmock_call_instance, fwk_id_t event_id);
void CMockExpectParameters_fwk_id_get_event_idx(CMOCK_fwk_id_get_event_idx_CALL_INSTANCE* cmock_call_instance, fwk_id_t event_id)
{
  memcpy((void*)(&cmock_call_instance->Expected_event_id), (void*)(&event_id),
         sizeof(fwk_id_t[sizeof(event_id) == sizeof(fwk_id_t) ? 1 : -1])); /* add fwk_id_t to :treat_as_array if this causes an error */
}

void fwk_id_get_event_idx_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, unsigned int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_fwk_id_get_event_idx_CALL_INSTANCE));
  CMOCK_fwk_id_get_event_idx_CALL_INSTANCE* cmock_call_instance = (CMOCK_fwk_id_get_event_idx_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.fwk_id_get_event_idx_CallInstance = CMock_Guts_MemChain(Mock.fwk_id_get_event_idx_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void fwk_id_get_event_idx_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, fwk_id_t event_id, unsigned int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_fwk_id_get_event_idx_CALL_INSTANCE));
  CMOCK_fwk_id_get_event_idx_CALL_INSTANCE* cmock_call_instance = (CMOCK_fwk_id_get_event_idx_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.fwk_id_get_event_idx_CallInstance = CMock_Guts_MemChain(Mock.fwk_id_get_event_idx_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_fwk_id_get_event_idx(cmock_call_instance, event_id);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

unsigned int fwk_id_get_notification_idx(fwk_id_t notification_id)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_fwk_id_get_notification_idx_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_fwk_id_get_notification_idx);
  cmock_call_instance = (CMOCK_fwk_id_get_notification_idx_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.fwk_id_get_notification_idx_CallInstance);
  Mock.fwk_id_get_notification_idx_CallInstance = CMock_Guts_MemNext(Mock.fwk_id_get_notification_idx_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  {
    UNITY_SET_DETAILS(CMockString_fwk_id_get_notification_idx,CMockString_notification_id);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_notification_id), (void*)(&notification_id), sizeof(fwk_id_t), cmock_line, CMockStringMismatch);
  }
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_fwk_id_get_notification_idx(CMOCK_fwk_id_get_notification_idx_CALL_INSTANCE* cmock_call_instance, fwk_id_t notification_id);
void CMockExpectParameters_fwk_id_get_notification_idx(CMOCK_fwk_id_get_notification_idx_CALL_INSTANCE* cmock_call_instance, fwk_id_t notification_id)
{
  memcpy((void*)(&cmock_call_instance->Expected_notification_id), (void*)(&notification_id),
         sizeof(fwk_id_t[sizeof(notification_id) == sizeof(fwk_id_t) ? 1 : -1])); /* add fwk_id_t to :treat_as_array if this causes an error */
}

void fwk_id_get_notification_idx_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, unsigned int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_fwk_id_get_notification_idx_CALL_INSTANCE));
  CMOCK_fwk_id_get_notification_idx_CALL_INSTANCE* cmock_call_instance = (CMOCK_fwk_id_get_notification_idx_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.fwk_id_get_notification_idx_CallInstance = CMock_Guts_MemChain(Mock.fwk_id_get_notification_idx_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void fwk_id_get_notification_idx_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, fwk_id_t notification_id, unsigned int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_fwk_id_get_notification_idx_CALL_INSTANCE));
  CMOCK_fwk_id_get_notification_idx_CALL_INSTANCE* cmock_call_instance = (CMOCK_fwk_id_get_notification_idx_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.fwk_id_get_notification_idx_CallInstance = CMock_Guts_MemChain(Mock.fwk_id_get_notification_idx_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_fwk_id_get_notification_idx(cmock_call_instance, notification_id);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

struct fwk_id_verbose_fmt fwk_id_verbose_str(fwk_id_t id)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_fwk_id_verbose_str_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_fwk_id_verbose_str);
  cmock_call_instance = (CMOCK_fwk_id_verbose_str_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.fwk_id_verbose_str_CallInstance);
  Mock.fwk_id_verbose_str_CallInstance = CMock_Guts_MemNext(Mock.fwk_id_verbose_str_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  {
    UNITY_SET_DETAILS(CMockString_fwk_id_verbose_str,CMockString_id);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_id), (void*)(&id), sizeof(fwk_id_t), cmock_line, CMockStringMismatch);
  }
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_fwk_id_verbose_str(CMOCK_fwk_id_verbose_str_CALL_INSTANCE* cmock_call_instance, fwk_id_t id);
void CMockExpectParameters_fwk_id_verbose_str(CMOCK_fwk_id_verbose_str_CALL_INSTANCE* cmock_call_instance, fwk_id_t id)
{
  memcpy((void*)(&cmock_call_instance->Expected_id), (void*)(&id),
         sizeof(fwk_id_t[sizeof(id) == sizeof(fwk_id_t) ? 1 : -1])); /* add fwk_id_t to :treat_as_array if this causes an error */
}

void fwk_id_verbose_str_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, struct fwk_id_verbose_fmt cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_fwk_id_verbose_str_CALL_INSTANCE));
  CMOCK_fwk_id_verbose_str_CALL_INSTANCE* cmock_call_instance = (CMOCK_fwk_id_verbose_str_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.fwk_id_verbose_str_CallInstance = CMock_Guts_MemChain(Mock.fwk_id_verbose_str_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void fwk_id_verbose_str_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, fwk_id_t id, struct fwk_id_verbose_fmt cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_fwk_id_verbose_str_CALL_INSTANCE));
  CMOCK_fwk_id_verbose_str_CALL_INSTANCE* cmock_call_instance = (CMOCK_fwk_id_verbose_str_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.fwk_id_verbose_str_CallInstance = CMock_Guts_MemChain(Mock.fwk_id_verbose_str_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_fwk_id_verbose_str(cmock_call_instance, id);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(struct fwk_id_verbose_fmt[sizeof(cmock_to_return) == sizeof(struct fwk_id_verbose_fmt) ? 1 : -1])); /* add struct fwk_id_verbose_fmt to :treat_as_array if this causes an error */
}

