/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mockfwk_mm.h"

static const char* CMockString_alignment = "alignment";
static const char* CMockString_fwk_mm_alloc = "fwk_mm_alloc";
static const char* CMockString_fwk_mm_alloc_aligned = "fwk_mm_alloc_aligned";
static const char* CMockString_fwk_mm_alloc_notrap = "fwk_mm_alloc_notrap";
static const char* CMockString_fwk_mm_calloc = "fwk_mm_calloc";
static const char* CMockString_fwk_mm_calloc_aligned = "fwk_mm_calloc_aligned";
static const char* CMockString_fwk_mm_free = "fwk_mm_free";
static const char* CMockString_fwk_mm_realloc = "fwk_mm_realloc";
static const char* CMockString_num = "num";
static const char* CMockString_ptr = "ptr";
static const char* CMockString_size = "size";

typedef struct _CMOCK_fwk_mm_alloc_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  void* ReturnVal;
  size_t Expected_num;
  size_t Expected_size;

} CMOCK_fwk_mm_alloc_CALL_INSTANCE;

typedef struct _CMOCK_fwk_mm_alloc_notrap_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  void* ReturnVal;
  size_t Expected_num;
  size_t Expected_size;

} CMOCK_fwk_mm_alloc_notrap_CALL_INSTANCE;

typedef struct _CMOCK_fwk_mm_alloc_aligned_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  void* ReturnVal;
  size_t Expected_alignment;
  size_t Expected_num;
  size_t Expected_size;

} CMOCK_fwk_mm_alloc_aligned_CALL_INSTANCE;

typedef struct _CMOCK_fwk_mm_calloc_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  void* ReturnVal;
  size_t Expected_num;
  size_t Expected_size;

} CMOCK_fwk_mm_calloc_CALL_INSTANCE;

typedef struct _CMOCK_fwk_mm_calloc_aligned_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  void* ReturnVal;
  size_t Expected_alignment;
  size_t Expected_num;
  size_t Expected_size;

} CMOCK_fwk_mm_calloc_aligned_CALL_INSTANCE;

typedef struct _CMOCK_fwk_mm_realloc_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  void* ReturnVal;
  void* Expected_ptr;
  size_t Expected_num;
  size_t Expected_size;

} CMOCK_fwk_mm_realloc_CALL_INSTANCE;

typedef struct _CMOCK_fwk_mm_free_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  void* Expected_ptr;

} CMOCK_fwk_mm_free_CALL_INSTANCE;

static struct Mockfwk_mmInstance
{
  CMOCK_MEM_INDEX_TYPE fwk_mm_alloc_CallInstance;
  CMOCK_MEM_INDEX_TYPE fwk_mm_alloc_notrap_CallInstance;
  CMOCK_MEM_INDEX_TYPE fwk_mm_alloc_aligned_CallInstance;
  CMOCK_MEM_INDEX_TYPE fwk_mm_calloc_CallInstance;
  CMOCK_MEM_INDEX_TYPE fwk_mm_calloc_aligned_CallInstance;
  CMOCK_MEM_INDEX_TYPE fwk_mm_realloc_CallInstance;
  CMOCK_MEM_INDEX_TYPE fwk_mm_free_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockfwk_mm_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.fwk_mm_alloc_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_fwk_mm_alloc);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.fwk_mm_alloc_notrap_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_fwk_mm_alloc_notrap);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.fwk_mm_alloc_aligned_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_fwk_mm_alloc_aligned);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.fwk_mm_calloc_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_fwk_mm_calloc);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.fwk_mm_calloc_aligned_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_fwk_mm_calloc_aligned);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.fwk_mm_realloc_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_fwk_mm_realloc);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.fwk_mm_free_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_fwk_mm_free);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
}

void Mockfwk_mm_Init(void)
{
  Mockfwk_mm_Destroy();
}

void Mockfwk_mm_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void* fwk_mm_alloc(size_t num, size_t size)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_fwk_mm_alloc_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_fwk_mm_alloc);
  cmock_call_instance = (CMOCK_fwk_mm_alloc_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.fwk_mm_alloc_CallInstance);
  Mock.fwk_mm_alloc_CallInstance = CMock_Guts_MemNext(Mock.fwk_mm_alloc_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  {
    UNITY_SET_DETAILS(CMockString_fwk_mm_alloc,CMockString_num);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_num), (void*)(&num), sizeof(size_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_fwk_mm_alloc,CMockString_size);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_size), (void*)(&size), sizeof(size_t), cmock_line, CMockStringMismatch);
  }
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_fwk_mm_alloc(CMOCK_fwk_mm_alloc_CALL_INSTANCE* cmock_call_instance, size_t num, size_t size);
void CMockExpectParameters_fwk_mm_alloc(CMOCK_fwk_mm_alloc_CALL_INSTANCE* cmock_call_instance, size_t num, size_t size)
{
  memcpy((void*)(&cmock_call_instance->Expected_num), (void*)(&num),
         sizeof(size_t[sizeof(num) == sizeof(size_t) ? 1 : -1])); /* add size_t to :treat_as_array if this causes an error */
  memcpy((void*)(&cmock_call_instance->Expected_size), (void*)(&size),
         sizeof(size_t[sizeof(size) == sizeof(size_t) ? 1 : -1])); /* add size_t to :treat_as_array if this causes an error */
}

void fwk_mm_alloc_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, void* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_fwk_mm_alloc_CALL_INSTANCE));
  CMOCK_fwk_mm_alloc_CALL_INSTANCE* cmock_call_instance = (CMOCK_fwk_mm_alloc_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.fwk_mm_alloc_CallInstance = CMock_Guts_MemChain(Mock.fwk_mm_alloc_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void fwk_mm_alloc_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, size_t num, size_t size, void* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_fwk_mm_alloc_CALL_INSTANCE));
  CMOCK_fwk_mm_alloc_CALL_INSTANCE* cmock_call_instance = (CMOCK_fwk_mm_alloc_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.fwk_mm_alloc_CallInstance = CMock_Guts_MemChain(Mock.fwk_mm_alloc_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_fwk_mm_alloc(cmock_call_instance, num, size);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void* fwk_mm_alloc_notrap(size_t num, size_t size)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_fwk_mm_alloc_notrap_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_fwk_mm_alloc_notrap);
  cmock_call_instance = (CMOCK_fwk_mm_alloc_notrap_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.fwk_mm_alloc_notrap_CallInstance);
  Mock.fwk_mm_alloc_notrap_CallInstance = CMock_Guts_MemNext(Mock.fwk_mm_alloc_notrap_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  {
    UNITY_SET_DETAILS(CMockString_fwk_mm_alloc_notrap,CMockString_num);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_num), (void*)(&num), sizeof(size_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_fwk_mm_alloc_notrap,CMockString_size);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_size), (void*)(&size), sizeof(size_t), cmock_line, CMockStringMismatch);
  }
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_fwk_mm_alloc_notrap(CMOCK_fwk_mm_alloc_notrap_CALL_INSTANCE* cmock_call_instance, size_t num, size_t size);
void CMockExpectParameters_fwk_mm_alloc_notrap(CMOCK_fwk_mm_alloc_notrap_CALL_INSTANCE* cmock_call_instance, size_t num, size_t size)
{
  memcpy((void*)(&cmock_call_instance->Expected_num), (void*)(&num),
         sizeof(size_t[sizeof(num) == sizeof(size_t) ? 1 : -1])); /* add size_t to :treat_as_array if this causes an error */
  memcpy((void*)(&cmock_call_instance->Expected_size), (void*)(&size),
         sizeof(size_t[sizeof(size) == sizeof(size_t) ? 1 : -1])); /* add size_t to :treat_as_array if this causes an error */
}

void fwk_mm_alloc_notrap_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, void* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_fwk_mm_alloc_notrap_CALL_INSTANCE));
  CMOCK_fwk_mm_alloc_notrap_CALL_INSTANCE* cmock_call_instance = (CMOCK_fwk_mm_alloc_notrap_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.fwk_mm_alloc_notrap_CallInstance = CMock_Guts_MemChain(Mock.fwk_mm_alloc_notrap_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void fwk_mm_alloc_notrap_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, size_t num, size_t size, void* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_fwk_mm_alloc_notrap_CALL_INSTANCE));
  CMOCK_fwk_mm_alloc_notrap_CALL_INSTANCE* cmock_call_instance = (CMOCK_fwk_mm_alloc_notrap_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.fwk_mm_alloc_notrap_CallInstance = CMock_Guts_MemChain(Mock.fwk_mm_alloc_notrap_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_fwk_mm_alloc_notrap(cmock_call_instance, num, size);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void* fwk_mm_alloc_aligned(size_t alignment, size_t num, size_t size)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_fwk_mm_alloc_aligned_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_fwk_mm_alloc_aligned);
  cmock_call_instance = (CMOCK_fwk_mm_alloc_aligned_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.fwk_mm_alloc_aligned_CallInstance);
  Mock.fwk_mm_alloc_aligned_CallInstance = CMock_Guts_MemNext(Mock.fwk_mm_alloc_aligned_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  {
    UNITY_SET_DETAILS(CMockString_fwk_mm_alloc_aligned,CMockString_alignment);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_alignment), (void*)(&alignment), sizeof(size_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_fwk_mm_alloc_aligned,CMockString_num);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_num), (void*)(&num), sizeof(size_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_fwk_mm_alloc_aligned,CMockString_size);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_size), (void*)(&size), sizeof(size_t), cmock_line, CMockStringMismatch);
  }
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_fwk_mm_alloc_aligned(CMOCK_fwk_mm_alloc_aligned_CALL_INSTANCE* cmock_call_instance, size_t alignment, size_t num, size_t size);
void CMockExpectParameters_fwk_mm_alloc_aligned(CMOCK_fwk_mm_alloc_aligned_CALL_INSTANCE* cmock_call_instance, size_t alignment, size_t num, size_t size)
{
  memcpy((void*)(&cmock_call_instance->Expected_alignment), (void*)(&alignment),
         sizeof(size_t[sizeof(alignment) == sizeof(size_t) ? 1 : -1])); /* add size_t to :treat_as_array if this causes an error */
  memcpy((void*)(&cmock_call_instance->Expected_num), (void*)(&num),
         sizeof(size_t[sizeof(num) == sizeof(size_t) ? 1 : -1])); /* add size_t to :treat_as_array if this causes an error */
  memcpy((void*)(&cmock_call_instance->Expected_size), (void*)(&size),
         sizeof(size_t[sizeof(size) == sizeof(size_t) ? 1 : -1])); /* add size_t to :treat_as_array if this causes an error */
}

void fwk_mm_alloc_aligned_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, void* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_fwk_mm_alloc_aligned_CALL_INSTANCE));
  CMOCK_fwk_mm_alloc_aligned_CALL_INSTANCE* cmock_call_instance = (CMOCK_fwk_mm_alloc_aligned_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.fwk_mm_alloc_aligned_CallInstance = CMock_Guts_MemChain(Mock.fwk_mm_alloc_aligned_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void fwk_mm_alloc_aligned_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, size_t alignment, size_t num, size_t size, void* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_fwk_mm_alloc_aligned_CALL_INSTANCE));
  CMOCK_fwk_mm_alloc_aligned_CALL_INSTANCE* cmock_call_instance = (CMOCK_fwk_mm_alloc_aligned_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.fwk_mm_alloc_aligned_CallInstance = CMock_Guts_MemChain(Mock.fwk_mm_alloc_aligned_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_fwk_mm_alloc_aligned(cmock_call_instance, alignment, num, size);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void* fwk_mm_calloc(size_t num, size_t size)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_fwk_mm_calloc_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_fwk_mm_calloc);
  cmock_call_instance = (CMOCK_fwk_mm_calloc_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.fwk_mm_calloc_CallInstance);
  Mock.fwk_mm_calloc_CallInstance = CMock_Guts_MemNext(Mock.fwk_mm_calloc_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  {
    UNITY_SET_DETAILS(CMockString_fwk_mm_calloc,CMockString_num);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_num), (void*)(&num), sizeof(size_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_fwk_mm_calloc,CMockString_size);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_size), (void*)(&size), sizeof(size_t), cmock_line, CMockStringMismatch);
  }
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_fwk_mm_calloc(CMOCK_fwk_mm_calloc_CALL_INSTANCE* cmock_call_instance, size_t num, size_t size);
void CMockExpectParameters_fwk_mm_calloc(CMOCK_fwk_mm_calloc_CALL_INSTANCE* cmock_call_instance, size_t num, size_t size)
{
  memcpy((void*)(&cmock_call_instance->Expected_num), (void*)(&num),
         sizeof(size_t[sizeof(num) == sizeof(size_t) ? 1 : -1])); /* add size_t to :treat_as_array if this causes an error */
  memcpy((void*)(&cmock_call_instance->Expected_size), (void*)(&size),
         sizeof(size_t[sizeof(size) == sizeof(size_t) ? 1 : -1])); /* add size_t to :treat_as_array if this causes an error */
}

void fwk_mm_calloc_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, void* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_fwk_mm_calloc_CALL_INSTANCE));
  CMOCK_fwk_mm_calloc_CALL_INSTANCE* cmock_call_instance = (CMOCK_fwk_mm_calloc_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.fwk_mm_calloc_CallInstance = CMock_Guts_MemChain(Mock.fwk_mm_calloc_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void fwk_mm_calloc_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, size_t num, size_t size, void* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_fwk_mm_calloc_CALL_INSTANCE));
  CMOCK_fwk_mm_calloc_CALL_INSTANCE* cmock_call_instance = (CMOCK_fwk_mm_calloc_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.fwk_mm_calloc_CallInstance = CMock_Guts_MemChain(Mock.fwk_mm_calloc_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_fwk_mm_calloc(cmock_call_instance, num, size);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void* fwk_mm_calloc_aligned(size_t alignment, size_t num, size_t size)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_fwk_mm_calloc_aligned_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_fwk_mm_calloc_aligned);
  cmock_call_instance = (CMOCK_fwk_mm_calloc_aligned_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.fwk_mm_calloc_aligned_CallInstance);
  Mock.fwk_mm_calloc_aligned_CallInstance = CMock_Guts_MemNext(Mock.fwk_mm_calloc_aligned_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  {
    UNITY_SET_DETAILS(CMockString_fwk_mm_calloc_aligned,CMockString_alignment);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_alignment), (void*)(&alignment), sizeof(size_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_fwk_mm_calloc_aligned,CMockString_num);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_num), (void*)(&num), sizeof(size_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_fwk_mm_calloc_aligned,CMockString_size);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_size), (void*)(&size), sizeof(size_t), cmock_line, CMockStringMismatch);
  }
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_fwk_mm_calloc_aligned(CMOCK_fwk_mm_calloc_aligned_CALL_INSTANCE* cmock_call_instance, size_t alignment, size_t num, size_t size);
void CMockExpectParameters_fwk_mm_calloc_aligned(CMOCK_fwk_mm_calloc_aligned_CALL_INSTANCE* cmock_call_instance, size_t alignment, size_t num, size_t size)
{
  memcpy((void*)(&cmock_call_instance->Expected_alignment), (void*)(&alignment),
         sizeof(size_t[sizeof(alignment) == sizeof(size_t) ? 1 : -1])); /* add size_t to :treat_as_array if this causes an error */
  memcpy((void*)(&cmock_call_instance->Expected_num), (void*)(&num),
         sizeof(size_t[sizeof(num) == sizeof(size_t) ? 1 : -1])); /* add size_t to :treat_as_array if this causes an error */
  memcpy((void*)(&cmock_call_instance->Expected_size), (void*)(&size),
         sizeof(size_t[sizeof(size) == sizeof(size_t) ? 1 : -1])); /* add size_t to :treat_as_array if this causes an error */
}

void fwk_mm_calloc_aligned_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, void* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_fwk_mm_calloc_aligned_CALL_INSTANCE));
  CMOCK_fwk_mm_calloc_aligned_CALL_INSTANCE* cmock_call_instance = (CMOCK_fwk_mm_calloc_aligned_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.fwk_mm_calloc_aligned_CallInstance = CMock_Guts_MemChain(Mock.fwk_mm_calloc_aligned_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void fwk_mm_calloc_aligned_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, size_t alignment, size_t num, size_t size, void* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_fwk_mm_calloc_aligned_CALL_INSTANCE));
  CMOCK_fwk_mm_calloc_aligned_CALL_INSTANCE* cmock_call_instance = (CMOCK_fwk_mm_calloc_aligned_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.fwk_mm_calloc_aligned_CallInstance = CMock_Guts_MemChain(Mock.fwk_mm_calloc_aligned_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_fwk_mm_calloc_aligned(cmock_call_instance, alignment, num, size);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void* fwk_mm_realloc(void* ptr, size_t num, size_t size)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_fwk_mm_realloc_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_fwk_mm_realloc);
  cmock_call_instance = (CMOCK_fwk_mm_realloc_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.fwk_mm_realloc_CallInstance);
  Mock.fwk_mm_realloc_CallInstance = CMock_Guts_MemNext(Mock.fwk_mm_realloc_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  {
    UNITY_SET_DETAILS(CMockString_fwk_mm_realloc,CMockString_ptr);
    if (cmock_call_instance->Expected_ptr == NULL)
      { UNITY_TEST_ASSERT_NULL(ptr, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_ptr, ptr, 1, cmock_line, CMockStringMismatch); }
  }
  {
    UNITY_SET_DETAILS(CMockString_fwk_mm_realloc,CMockString_num);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_num), (void*)(&num), sizeof(size_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_fwk_mm_realloc,CMockString_size);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_size), (void*)(&size), sizeof(size_t), cmock_line, CMockStringMismatch);
  }
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_fwk_mm_realloc(CMOCK_fwk_mm_realloc_CALL_INSTANCE* cmock_call_instance, void* ptr, size_t num, size_t size);
void CMockExpectParameters_fwk_mm_realloc(CMOCK_fwk_mm_realloc_CALL_INSTANCE* cmock_call_instance, void* ptr, size_t num, size_t size)
{
  cmock_call_instance->Expected_ptr = ptr;
  memcpy((void*)(&cmock_call_instance->Expected_num), (void*)(&num),
         sizeof(size_t[sizeof(num) == sizeof(size_t) ? 1 : -1])); /* add size_t to :treat_as_array if this causes an error */
  memcpy((void*)(&cmock_call_instance->Expected_size), (void*)(&size),
         sizeof(size_t[sizeof(size) == sizeof(size_t) ? 1 : -1])); /* add size_t to :treat_as_array if this causes an error */
}

void fwk_mm_realloc_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, void* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_fwk_mm_realloc_CALL_INSTANCE));
  CMOCK_fwk_mm_realloc_CALL_INSTANCE* cmock_call_instance = (CMOCK_fwk_mm_realloc_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.fwk_mm_realloc_CallInstance = CMock_Guts_MemChain(Mock.fwk_mm_realloc_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void fwk_mm_realloc_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, void* ptr, size_t num, size_t size, void* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_fwk_mm_realloc_CALL_INSTANCE));
  CMOCK_fwk_mm_realloc_CALL_INSTANCE* cmock_call_instance = (CMOCK_fwk_mm_realloc_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.fwk_mm_realloc_CallInstance = CMock_Guts_MemChain(Mock.fwk_mm_realloc_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_fwk_mm_realloc(cmock_call_instance, ptr, num, size);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void fwk_mm_free(void* ptr)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_fwk_mm_free_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_fwk_mm_free);
  cmock_call_instance = (CMOCK_fwk_mm_free_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.fwk_mm_free_CallInstance);
  Mock.fwk_mm_free_CallInstance = CMock_Guts_MemNext(Mock.fwk_mm_free_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  {
    UNITY_SET_DETAILS(CMockString_fwk_mm_free,CMockString_ptr);
    if (cmock_call_instance->Expected_ptr == NULL)
      { UNITY_TEST_ASSERT_NULL(ptr, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_ptr, ptr, 1, cmock_line, CMockStringMismatch); }
  }
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_fwk_mm_free(CMOCK_fwk_mm_free_CALL_INSTANCE* cmock_call_instance, void* ptr);
void CMockExpectParameters_fwk_mm_free(CMOCK_fwk_mm_free_CALL_INSTANCE* cmock_call_instance, void* ptr)
{
  cmock_call_instance->Expected_ptr = ptr;
}

void fwk_mm_free_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_fwk_mm_free_CALL_INSTANCE));
  CMOCK_fwk_mm_free_CALL_INSTANCE* cmock_call_instance = (CMOCK_fwk_mm_free_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.fwk_mm_free_CallInstance = CMock_Guts_MemChain(Mock.fwk_mm_free_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void fwk_mm_free_CMockExpect(UNITY_LINE_TYPE cmock_line, void* ptr)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_fwk_mm_free_CALL_INSTANCE));
  CMOCK_fwk_mm_free_CALL_INSTANCE* cmock_call_instance = (CMOCK_fwk_mm_free_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.fwk_mm_free_CallInstance = CMock_Guts_MemChain(Mock.fwk_mm_free_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_fwk_mm_free(cmock_call_instance, ptr);
}

