/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mockfwk_io.h"

static const char* CMockString_args = "args";
static const char* CMockString_buffer = "buffer";
static const char* CMockString_ch = "ch";
static const char* CMockString_count = "count";
static const char* CMockString_format = "format";
static const char* CMockString_fwk_io_close = "fwk_io_close";
static const char* CMockString_fwk_io_getch = "fwk_io_getch";
static const char* CMockString_fwk_io_init = "fwk_io_init";
static const char* CMockString_fwk_io_open = "fwk_io_open";
static const char* CMockString_fwk_io_printf = "fwk_io_printf";
static const char* CMockString_fwk_io_putch = "fwk_io_putch";
static const char* CMockString_fwk_io_puts = "fwk_io_puts";
static const char* CMockString_fwk_io_read = "fwk_io_read";
static const char* CMockString_fwk_io_vprintf = "fwk_io_vprintf";
static const char* CMockString_fwk_io_write = "fwk_io_write";
static const char* CMockString_id = "id";
static const char* CMockString_mode = "mode";
static const char* CMockString_read = "read";
static const char* CMockString_size = "size";
static const char* CMockString_str = "str";
static const char* CMockString_stream = "stream";
static const char* CMockString_written = "written";

typedef struct _CMOCK_fwk_io_open_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int ReturnVal;
  struct fwk_io_stream* Expected_stream;
  fwk_id_t Expected_id;
  enum fwk_io_mode Expected_mode;

} CMOCK_fwk_io_open_CALL_INSTANCE;

typedef struct _CMOCK_fwk_io_getch_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int ReturnVal;
  const struct fwk_io_stream* Expected_stream;
  char* Expected_ch;

} CMOCK_fwk_io_getch_CALL_INSTANCE;

typedef struct _CMOCK_fwk_io_putch_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int ReturnVal;
  const struct fwk_io_stream* Expected_stream;
  char Expected_ch;

} CMOCK_fwk_io_putch_CALL_INSTANCE;

typedef struct _CMOCK_fwk_io_read_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int ReturnVal;
  const struct fwk_io_stream* Expected_stream;
  size_t* Expected_read;
  void* Expected_buffer;
  size_t Expected_size;
  size_t Expected_count;

} CMOCK_fwk_io_read_CALL_INSTANCE;

typedef struct _CMOCK_fwk_io_write_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int ReturnVal;
  const struct fwk_io_stream* Expected_stream;
  size_t* Expected_written;
  const void* Expected_buffer;
  size_t Expected_size;
  size_t Expected_count;

} CMOCK_fwk_io_write_CALL_INSTANCE;

typedef struct _CMOCK_fwk_io_puts_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int ReturnVal;
  const struct fwk_io_stream* Expected_stream;
  const char* Expected_str;

} CMOCK_fwk_io_puts_CALL_INSTANCE;

typedef struct _CMOCK_fwk_io_vprintf_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int ReturnVal;
  const struct fwk_io_stream* Expected_stream;
  const char* Expected_format;
  va_list Expected_args;

} CMOCK_fwk_io_vprintf_CALL_INSTANCE;

typedef struct _CMOCK_fwk_io_printf_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int ReturnVal;
  const struct fwk_io_stream* Expected_stream;
  const char* Expected_format;

} CMOCK_fwk_io_printf_CALL_INSTANCE;

typedef struct _CMOCK_fwk_io_close_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int ReturnVal;
  struct fwk_io_stream* Expected_stream;

} CMOCK_fwk_io_close_CALL_INSTANCE;

typedef struct _CMOCK_fwk_io_init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int ReturnVal;

} CMOCK_fwk_io_init_CALL_INSTANCE;

static struct Mockfwk_ioInstance
{
  CMOCK_MEM_INDEX_TYPE fwk_io_open_CallInstance;
  CMOCK_MEM_INDEX_TYPE fwk_io_getch_CallInstance;
  CMOCK_MEM_INDEX_TYPE fwk_io_putch_CallInstance;
  CMOCK_MEM_INDEX_TYPE fwk_io_read_CallInstance;
  CMOCK_MEM_INDEX_TYPE fwk_io_write_CallInstance;
  CMOCK_MEM_INDEX_TYPE fwk_io_puts_CallInstance;
  CMOCK_MEM_INDEX_TYPE fwk_io_vprintf_CallInstance;
  CMOCK_MEM_INDEX_TYPE fwk_io_printf_CallInstance;
  CMOCK_MEM_INDEX_TYPE fwk_io_close_CallInstance;
  CMOCK_MEM_INDEX_TYPE fwk_io_init_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockfwk_io_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.fwk_io_open_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_fwk_io_open);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.fwk_io_getch_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_fwk_io_getch);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.fwk_io_putch_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_fwk_io_putch);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.fwk_io_read_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_fwk_io_read);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.fwk_io_write_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_fwk_io_write);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.fwk_io_puts_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_fwk_io_puts);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.fwk_io_vprintf_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_fwk_io_vprintf);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.fwk_io_printf_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_fwk_io_printf);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.fwk_io_close_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_fwk_io_close);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.fwk_io_init_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_fwk_io_init);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
}

void Mockfwk_io_Init(void)
{
  Mockfwk_io_Destroy();
}

void Mockfwk_io_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

int fwk_io_open(struct fwk_io_stream* stream, fwk_id_t id, enum fwk_io_mode mode)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_fwk_io_open_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_fwk_io_open);
  cmock_call_instance = (CMOCK_fwk_io_open_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.fwk_io_open_CallInstance);
  Mock.fwk_io_open_CallInstance = CMock_Guts_MemNext(Mock.fwk_io_open_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  {
    UNITY_SET_DETAILS(CMockString_fwk_io_open,CMockString_stream);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_stream), (void*)(stream), sizeof(struct fwk_io_stream), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_fwk_io_open,CMockString_id);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_id), (void*)(&id), sizeof(fwk_id_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_fwk_io_open,CMockString_mode);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_mode), (void*)(&mode), sizeof(enum fwk_io_mode), cmock_line, CMockStringMismatch);
  }
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_fwk_io_open(CMOCK_fwk_io_open_CALL_INSTANCE* cmock_call_instance, struct fwk_io_stream* stream, fwk_id_t id, enum fwk_io_mode mode);
void CMockExpectParameters_fwk_io_open(CMOCK_fwk_io_open_CALL_INSTANCE* cmock_call_instance, struct fwk_io_stream* stream, fwk_id_t id, enum fwk_io_mode mode)
{
  cmock_call_instance->Expected_stream = stream;
  memcpy((void*)(&cmock_call_instance->Expected_id), (void*)(&id),
         sizeof(fwk_id_t[sizeof(id) == sizeof(fwk_id_t) ? 1 : -1])); /* add fwk_id_t to :treat_as_array if this causes an error */
  memcpy((void*)(&cmock_call_instance->Expected_mode), (void*)(&mode),
         sizeof(enum fwk_io_mode[sizeof(mode) == sizeof(enum fwk_io_mode) ? 1 : -1])); /* add enum fwk_io_mode to :treat_as_array if this causes an error */
}

void fwk_io_open_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_fwk_io_open_CALL_INSTANCE));
  CMOCK_fwk_io_open_CALL_INSTANCE* cmock_call_instance = (CMOCK_fwk_io_open_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.fwk_io_open_CallInstance = CMock_Guts_MemChain(Mock.fwk_io_open_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void fwk_io_open_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, struct fwk_io_stream* stream, fwk_id_t id, enum fwk_io_mode mode, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_fwk_io_open_CALL_INSTANCE));
  CMOCK_fwk_io_open_CALL_INSTANCE* cmock_call_instance = (CMOCK_fwk_io_open_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.fwk_io_open_CallInstance = CMock_Guts_MemChain(Mock.fwk_io_open_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_fwk_io_open(cmock_call_instance, stream, id, mode);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

int fwk_io_getch(const struct fwk_io_stream* stream, char* ch)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_fwk_io_getch_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_fwk_io_getch);
  cmock_call_instance = (CMOCK_fwk_io_getch_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.fwk_io_getch_CallInstance);
  Mock.fwk_io_getch_CallInstance = CMock_Guts_MemNext(Mock.fwk_io_getch_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  {
    UNITY_SET_DETAILS(CMockString_fwk_io_getch,CMockString_stream);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_stream), (void*)(stream), sizeof(const struct fwk_io_stream), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_fwk_io_getch,CMockString_ch);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_ch, ch, cmock_line, CMockStringMismatch);
  }
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_fwk_io_getch(CMOCK_fwk_io_getch_CALL_INSTANCE* cmock_call_instance, const struct fwk_io_stream* stream, char* ch);
void CMockExpectParameters_fwk_io_getch(CMOCK_fwk_io_getch_CALL_INSTANCE* cmock_call_instance, const struct fwk_io_stream* stream, char* ch)
{
  cmock_call_instance->Expected_stream = stream;
  cmock_call_instance->Expected_ch = ch;
}

void fwk_io_getch_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_fwk_io_getch_CALL_INSTANCE));
  CMOCK_fwk_io_getch_CALL_INSTANCE* cmock_call_instance = (CMOCK_fwk_io_getch_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.fwk_io_getch_CallInstance = CMock_Guts_MemChain(Mock.fwk_io_getch_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void fwk_io_getch_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const struct fwk_io_stream* stream, char* ch, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_fwk_io_getch_CALL_INSTANCE));
  CMOCK_fwk_io_getch_CALL_INSTANCE* cmock_call_instance = (CMOCK_fwk_io_getch_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.fwk_io_getch_CallInstance = CMock_Guts_MemChain(Mock.fwk_io_getch_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_fwk_io_getch(cmock_call_instance, stream, ch);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

int fwk_io_putch(const struct fwk_io_stream* stream, char ch)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_fwk_io_putch_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_fwk_io_putch);
  cmock_call_instance = (CMOCK_fwk_io_putch_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.fwk_io_putch_CallInstance);
  Mock.fwk_io_putch_CallInstance = CMock_Guts_MemNext(Mock.fwk_io_putch_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  {
    UNITY_SET_DETAILS(CMockString_fwk_io_putch,CMockString_stream);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_stream), (void*)(stream), sizeof(const struct fwk_io_stream), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_fwk_io_putch,CMockString_ch);
    UNITY_TEST_ASSERT_EQUAL_INT8(cmock_call_instance->Expected_ch, ch, cmock_line, CMockStringMismatch);
  }
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_fwk_io_putch(CMOCK_fwk_io_putch_CALL_INSTANCE* cmock_call_instance, const struct fwk_io_stream* stream, char ch);
void CMockExpectParameters_fwk_io_putch(CMOCK_fwk_io_putch_CALL_INSTANCE* cmock_call_instance, const struct fwk_io_stream* stream, char ch)
{
  cmock_call_instance->Expected_stream = stream;
  cmock_call_instance->Expected_ch = ch;
}

void fwk_io_putch_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_fwk_io_putch_CALL_INSTANCE));
  CMOCK_fwk_io_putch_CALL_INSTANCE* cmock_call_instance = (CMOCK_fwk_io_putch_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.fwk_io_putch_CallInstance = CMock_Guts_MemChain(Mock.fwk_io_putch_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void fwk_io_putch_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const struct fwk_io_stream* stream, char ch, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_fwk_io_putch_CALL_INSTANCE));
  CMOCK_fwk_io_putch_CALL_INSTANCE* cmock_call_instance = (CMOCK_fwk_io_putch_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.fwk_io_putch_CallInstance = CMock_Guts_MemChain(Mock.fwk_io_putch_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_fwk_io_putch(cmock_call_instance, stream, ch);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

int fwk_io_read(const struct fwk_io_stream* stream, size_t* read, void* buffer, size_t size, size_t count)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_fwk_io_read_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_fwk_io_read);
  cmock_call_instance = (CMOCK_fwk_io_read_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.fwk_io_read_CallInstance);
  Mock.fwk_io_read_CallInstance = CMock_Guts_MemNext(Mock.fwk_io_read_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  {
    UNITY_SET_DETAILS(CMockString_fwk_io_read,CMockString_stream);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_stream), (void*)(stream), sizeof(const struct fwk_io_stream), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_fwk_io_read,CMockString_read);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_read), (void*)(read), sizeof(size_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_fwk_io_read,CMockString_buffer);
    if (cmock_call_instance->Expected_buffer == NULL)
      { UNITY_TEST_ASSERT_NULL(buffer, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_buffer, buffer, 1, cmock_line, CMockStringMismatch); }
  }
  {
    UNITY_SET_DETAILS(CMockString_fwk_io_read,CMockString_size);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_size), (void*)(&size), sizeof(size_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_fwk_io_read,CMockString_count);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_count), (void*)(&count), sizeof(size_t), cmock_line, CMockStringMismatch);
  }
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_fwk_io_read(CMOCK_fwk_io_read_CALL_INSTANCE* cmock_call_instance, const struct fwk_io_stream* stream, size_t* read, void* buffer, size_t size, size_t count);
void CMockExpectParameters_fwk_io_read(CMOCK_fwk_io_read_CALL_INSTANCE* cmock_call_instance, const struct fwk_io_stream* stream, size_t* read, void* buffer, size_t size, size_t count)
{
  cmock_call_instance->Expected_stream = stream;
  cmock_call_instance->Expected_read = read;
  cmock_call_instance->Expected_buffer = buffer;
  memcpy((void*)(&cmock_call_instance->Expected_size), (void*)(&size),
         sizeof(size_t[sizeof(size) == sizeof(size_t) ? 1 : -1])); /* add size_t to :treat_as_array if this causes an error */
  memcpy((void*)(&cmock_call_instance->Expected_count), (void*)(&count),
         sizeof(size_t[sizeof(count) == sizeof(size_t) ? 1 : -1])); /* add size_t to :treat_as_array if this causes an error */
}

void fwk_io_read_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_fwk_io_read_CALL_INSTANCE));
  CMOCK_fwk_io_read_CALL_INSTANCE* cmock_call_instance = (CMOCK_fwk_io_read_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.fwk_io_read_CallInstance = CMock_Guts_MemChain(Mock.fwk_io_read_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void fwk_io_read_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const struct fwk_io_stream* stream, size_t* read, void* buffer, size_t size, size_t count, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_fwk_io_read_CALL_INSTANCE));
  CMOCK_fwk_io_read_CALL_INSTANCE* cmock_call_instance = (CMOCK_fwk_io_read_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.fwk_io_read_CallInstance = CMock_Guts_MemChain(Mock.fwk_io_read_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_fwk_io_read(cmock_call_instance, stream, read, buffer, size, count);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

int fwk_io_write(const struct fwk_io_stream* stream, size_t* written, const void* buffer, size_t size, size_t count)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_fwk_io_write_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_fwk_io_write);
  cmock_call_instance = (CMOCK_fwk_io_write_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.fwk_io_write_CallInstance);
  Mock.fwk_io_write_CallInstance = CMock_Guts_MemNext(Mock.fwk_io_write_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  {
    UNITY_SET_DETAILS(CMockString_fwk_io_write,CMockString_stream);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_stream), (void*)(stream), sizeof(const struct fwk_io_stream), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_fwk_io_write,CMockString_written);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_written), (void*)(written), sizeof(size_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_fwk_io_write,CMockString_buffer);
    if (cmock_call_instance->Expected_buffer == NULL)
      { UNITY_TEST_ASSERT_NULL(buffer, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_buffer, buffer, 1, cmock_line, CMockStringMismatch); }
  }
  {
    UNITY_SET_DETAILS(CMockString_fwk_io_write,CMockString_size);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_size), (void*)(&size), sizeof(size_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_fwk_io_write,CMockString_count);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_count), (void*)(&count), sizeof(size_t), cmock_line, CMockStringMismatch);
  }
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_fwk_io_write(CMOCK_fwk_io_write_CALL_INSTANCE* cmock_call_instance, const struct fwk_io_stream* stream, size_t* written, const void* buffer, size_t size, size_t count);
void CMockExpectParameters_fwk_io_write(CMOCK_fwk_io_write_CALL_INSTANCE* cmock_call_instance, const struct fwk_io_stream* stream, size_t* written, const void* buffer, size_t size, size_t count)
{
  cmock_call_instance->Expected_stream = stream;
  cmock_call_instance->Expected_written = written;
  cmock_call_instance->Expected_buffer = buffer;
  memcpy((void*)(&cmock_call_instance->Expected_size), (void*)(&size),
         sizeof(size_t[sizeof(size) == sizeof(size_t) ? 1 : -1])); /* add size_t to :treat_as_array if this causes an error */
  memcpy((void*)(&cmock_call_instance->Expected_count), (void*)(&count),
         sizeof(size_t[sizeof(count) == sizeof(size_t) ? 1 : -1])); /* add size_t to :treat_as_array if this causes an error */
}

void fwk_io_write_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_fwk_io_write_CALL_INSTANCE));
  CMOCK_fwk_io_write_CALL_INSTANCE* cmock_call_instance = (CMOCK_fwk_io_write_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.fwk_io_write_CallInstance = CMock_Guts_MemChain(Mock.fwk_io_write_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void fwk_io_write_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const struct fwk_io_stream* stream, size_t* written, const void* buffer, size_t size, size_t count, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_fwk_io_write_CALL_INSTANCE));
  CMOCK_fwk_io_write_CALL_INSTANCE* cmock_call_instance = (CMOCK_fwk_io_write_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.fwk_io_write_CallInstance = CMock_Guts_MemChain(Mock.fwk_io_write_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_fwk_io_write(cmock_call_instance, stream, written, buffer, size, count);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

int fwk_io_puts(const struct fwk_io_stream* stream, const char* str)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_fwk_io_puts_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_fwk_io_puts);
  cmock_call_instance = (CMOCK_fwk_io_puts_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.fwk_io_puts_CallInstance);
  Mock.fwk_io_puts_CallInstance = CMock_Guts_MemNext(Mock.fwk_io_puts_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  {
    UNITY_SET_DETAILS(CMockString_fwk_io_puts,CMockString_stream);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_stream), (void*)(stream), sizeof(const struct fwk_io_stream), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_fwk_io_puts,CMockString_str);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_str, str, cmock_line, CMockStringMismatch);
  }
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_fwk_io_puts(CMOCK_fwk_io_puts_CALL_INSTANCE* cmock_call_instance, const struct fwk_io_stream* stream, const char* str);
void CMockExpectParameters_fwk_io_puts(CMOCK_fwk_io_puts_CALL_INSTANCE* cmock_call_instance, const struct fwk_io_stream* stream, const char* str)
{
  cmock_call_instance->Expected_stream = stream;
  cmock_call_instance->Expected_str = str;
}

void fwk_io_puts_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_fwk_io_puts_CALL_INSTANCE));
  CMOCK_fwk_io_puts_CALL_INSTANCE* cmock_call_instance = (CMOCK_fwk_io_puts_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.fwk_io_puts_CallInstance = CMock_Guts_MemChain(Mock.fwk_io_puts_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void fwk_io_puts_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const struct fwk_io_stream* stream, const char* str, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_fwk_io_puts_CALL_INSTANCE));
  CMOCK_fwk_io_puts_CALL_INSTANCE* cmock_call_instance = (CMOCK_fwk_io_puts_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.fwk_io_puts_CallInstance = CMock_Guts_MemChain(Mock.fwk_io_puts_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_fwk_io_puts(cmock_call_instance, stream, str);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

int fwk_io_vprintf(const struct fwk_io_stream* stream, const char* format, va_list args)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_fwk_io_vprintf_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_fwk_io_vprintf);
  cmock_call_instance = (CMOCK_fwk_io_vprintf_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.fwk_io_vprintf_CallInstance);
  Mock.fwk_io_vprintf_CallInstance = CMock_Guts_MemNext(Mock.fwk_io_vprintf_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  {
    UNITY_SET_DETAILS(CMockString_fwk_io_vprintf,CMockString_stream);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_stream), (void*)(stream), sizeof(const struct fwk_io_stream), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_fwk_io_vprintf,CMockString_format);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_format, format, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_fwk_io_vprintf,CMockString_args);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_args), (void*)(&args), sizeof(va_list), cmock_line, CMockStringMismatch);
  }
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_fwk_io_vprintf(CMOCK_fwk_io_vprintf_CALL_INSTANCE* cmock_call_instance, const struct fwk_io_stream* stream, const char* format, va_list args);
void CMockExpectParameters_fwk_io_vprintf(CMOCK_fwk_io_vprintf_CALL_INSTANCE* cmock_call_instance, const struct fwk_io_stream* stream, const char* format, va_list args)
{
  cmock_call_instance->Expected_stream = stream;
  cmock_call_instance->Expected_format = format;
  memcpy((void*)(&cmock_call_instance->Expected_args), (void*)(&args),
         sizeof(va_list[sizeof(args) == sizeof(va_list) ? 1 : -1])); /* add va_list to :treat_as_array if this causes an error */
}

void fwk_io_vprintf_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_fwk_io_vprintf_CALL_INSTANCE));
  CMOCK_fwk_io_vprintf_CALL_INSTANCE* cmock_call_instance = (CMOCK_fwk_io_vprintf_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.fwk_io_vprintf_CallInstance = CMock_Guts_MemChain(Mock.fwk_io_vprintf_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void fwk_io_vprintf_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const struct fwk_io_stream* stream, const char* format, va_list args, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_fwk_io_vprintf_CALL_INSTANCE));
  CMOCK_fwk_io_vprintf_CALL_INSTANCE* cmock_call_instance = (CMOCK_fwk_io_vprintf_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.fwk_io_vprintf_CallInstance = CMock_Guts_MemChain(Mock.fwk_io_vprintf_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_fwk_io_vprintf(cmock_call_instance, stream, format, args);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

int fwk_io_printf(const struct fwk_io_stream* stream, const char* format, ...)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_fwk_io_printf_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_fwk_io_printf);
  cmock_call_instance = (CMOCK_fwk_io_printf_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.fwk_io_printf_CallInstance);
  Mock.fwk_io_printf_CallInstance = CMock_Guts_MemNext(Mock.fwk_io_printf_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  {
    UNITY_SET_DETAILS(CMockString_fwk_io_printf,CMockString_stream);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_stream), (void*)(stream), sizeof(const struct fwk_io_stream), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_fwk_io_printf,CMockString_format);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_format, format, cmock_line, CMockStringMismatch);
  }
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_fwk_io_printf(CMOCK_fwk_io_printf_CALL_INSTANCE* cmock_call_instance, const struct fwk_io_stream* stream, const char* format);
void CMockExpectParameters_fwk_io_printf(CMOCK_fwk_io_printf_CALL_INSTANCE* cmock_call_instance, const struct fwk_io_stream* stream, const char* format)
{
  cmock_call_instance->Expected_stream = stream;
  cmock_call_instance->Expected_format = format;
}

void fwk_io_printf_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_fwk_io_printf_CALL_INSTANCE));
  CMOCK_fwk_io_printf_CALL_INSTANCE* cmock_call_instance = (CMOCK_fwk_io_printf_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.fwk_io_printf_CallInstance = CMock_Guts_MemChain(Mock.fwk_io_printf_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void fwk_io_printf_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const struct fwk_io_stream* stream, const char* format, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_fwk_io_printf_CALL_INSTANCE));
  CMOCK_fwk_io_printf_CALL_INSTANCE* cmock_call_instance = (CMOCK_fwk_io_printf_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.fwk_io_printf_CallInstance = CMock_Guts_MemChain(Mock.fwk_io_printf_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_fwk_io_printf(cmock_call_instance, stream, format);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

int fwk_io_close(struct fwk_io_stream* stream)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_fwk_io_close_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_fwk_io_close);
  cmock_call_instance = (CMOCK_fwk_io_close_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.fwk_io_close_CallInstance);
  Mock.fwk_io_close_CallInstance = CMock_Guts_MemNext(Mock.fwk_io_close_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  {
    UNITY_SET_DETAILS(CMockString_fwk_io_close,CMockString_stream);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_stream), (void*)(stream), sizeof(struct fwk_io_stream), cmock_line, CMockStringMismatch);
  }
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_fwk_io_close(CMOCK_fwk_io_close_CALL_INSTANCE* cmock_call_instance, struct fwk_io_stream* stream);
void CMockExpectParameters_fwk_io_close(CMOCK_fwk_io_close_CALL_INSTANCE* cmock_call_instance, struct fwk_io_stream* stream)
{
  cmock_call_instance->Expected_stream = stream;
}

void fwk_io_close_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_fwk_io_close_CALL_INSTANCE));
  CMOCK_fwk_io_close_CALL_INSTANCE* cmock_call_instance = (CMOCK_fwk_io_close_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.fwk_io_close_CallInstance = CMock_Guts_MemChain(Mock.fwk_io_close_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void fwk_io_close_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, struct fwk_io_stream* stream, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_fwk_io_close_CALL_INSTANCE));
  CMOCK_fwk_io_close_CALL_INSTANCE* cmock_call_instance = (CMOCK_fwk_io_close_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.fwk_io_close_CallInstance = CMock_Guts_MemChain(Mock.fwk_io_close_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_fwk_io_close(cmock_call_instance, stream);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

int fwk_io_init(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_fwk_io_init_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_fwk_io_init);
  cmock_call_instance = (CMOCK_fwk_io_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.fwk_io_init_CallInstance);
  Mock.fwk_io_init_CallInstance = CMock_Guts_MemNext(Mock.fwk_io_init_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void fwk_io_init_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_fwk_io_init_CALL_INSTANCE));
  CMOCK_fwk_io_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_fwk_io_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.fwk_io_init_CallInstance = CMock_Guts_MemChain(Mock.fwk_io_init_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

