/*
 * Arm SCP/MCP Software
 * Copyright (c) 2022, Arm Limited and Contributors. All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef TRANSPORT_INTERNAL_H
#define TRANSPORT_INTERNAL_H

#include <stdint.h>

#define MOD_TRANSPORT_MAX_CHANNELS 8

#define MOD_TRANSPORT_MAILBOX_STATUS_FREE_POS 0
#define MOD_TRANSPORT_MAILBOX_STATUS_FREE_MASK \
    (UINT32_C(0x1) << MOD_TRANSPORT_MAILBOX_STATUS_FREE_POS)

#define MOD_TRANSPORT_MAILBOX_FLAGS_IENABLED_POS 0
#define MOD_TRANSPORT_MAILBOX_FLAGS_IENABLED_MASK \
    (UINT32_C(0x1) << MOD_TRANSPORT_MAILBOX_FLAGS_IENABLED_POS)

#define MOD_TRANSPORT_MAILBOX_STATUS_ERROR_POS 1
#define MOD_TRANSPORT_MAILBOX_STATUS_ERROR_MASK \
    (UINT32_C(0x1) << MOD_TRANSPORT_MAILBOX_STATUS_ERROR_POS)

#endif /* TRANSPORT_INTERNAL_H */
