#
# Arm SCP/MCP Software
# Copyright (c) 2017-2019, Arm Limited and Contributors. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

BS_LIB_NAME := psu
BS_LIB_SOURCES := \
    mod_psu_device_api.c \
    mod_psu_event.c \
    mod_psu_module.c

include $(BS_DIR)/lib.mk
