#
# Arm SCP/MCP Software
# Copyright (c) 2017-2020, Arm Limited and Contributors. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

BS_LIB_NAME := CMN SKEENA

BS_LIB_SOURCES = mod_cmn_skeena.c
BS_LIB_SOURCES += cmn_skeena.c cmn_skeena_ccix.c

include $(BS_DIR)/lib.mk
