/*
 * Arm SCP/MCP Software
 * Copyright (c) 2020-2021, Arm Limited and Contributors. All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef CONFIG_MCP_PL011_H
#define CONFIG_MCP_PL011_H

#include <fwk_id.h>
#include <fwk_module_idx.h>

enum config_pl011_element_idx {
    CONFIG_PL011_ELEMENT_IDX_MCP_UART0,
    CONFIG_PL011_ELEMENT_IDX_MCP_UART1,
    CONFIG_PL011_ELEMENT_IDX_COUNT,
};

#define CONFIG_PL011_ELEMENT_ID_MCP_UART0_INIT \
    FWK_ID_ELEMENT_INIT( \
        FWK_MODULE_IDX_PL011, CONFIG_PL011_ELEMENT_IDX_MCP_UART0)

#define CONFIG_PL011_ELEMENT_ID_MCP_UART0 \
    FWK_ID_ELEMENT(FWK_MODULE_IDX_PL011, CONFIG_PL011_ELEMENT_IDX_MCP_UART0)

#define CONFIG_PL011_ELEMENT_ID_MCP_UART1_INIT \
    FWK_ID_ELEMENT_INIT( \
        FWK_MODULE_IDX_PL011, CONFIG_PL011_ELEMENT_IDX_MCP_UART1)

#define CONFIG_PL011_ELEMENT_ID_MCP_UART1 \
    FWK_ID_ELEMENT(FWK_MODULE_IDX_PL011, CONFIG_PL011_ELEMENT_IDX_MCP_UART1)

#endif /* CONFIG_MCP_PL011_H */
