#
# Arm SCP/MCP Software
# Copyright (c) 2018-2020, Arm Limited and Contributors. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

BS_LIB_NAME := "f_i2c"
BS_LIB_SOURCES = mod_f_i2c.c i2c_api.c i2c_depend.c i2c_driver.c i2c_reg_access.c

include $(BS_DIR)/lib.mk
