#
# Arm SCP/MCP Software
# Copyright (c) 2019-2020, Arm Limited and Contributors. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

BS_LIB_NAME := SCMI Reset Domain Protocol
BS_LIB_SOURCES := mod_scmi_reset_domain.c

include $(BS_DIR)/lib.mk
