#
# Renesas SCP/MCP Software
# Copyright (c) 2021, Renesas Electronics Corporation. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

BS_LIB_NAME := RCAR_PD_PMIC_BD9571
BS_LIB_SOURCES = mod_rcar_pd_pmic_bd9571.c

include $(BS_DIR)/lib.mk
