#
# Arm SCP/MCP Software
# Copyright (c) 2021, Arm Limited and Contributors. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

BS_LIB_NAME := mpmm
BS_LIB_SOURCES := mod_mpmm.c

include $(BS_DIR)/lib.mk
