/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKFWK_ID_INTERNAL_H
#define _MOCKFWK_ID_INTERNAL_H

#include "unity.h"
#include "internal/fwk_id.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void Mockfwk_id_internal_Init(void);
void Mockfwk_id_internal_Destroy(void);
void Mockfwk_id_internal_Verify(void);




#define __fwk_id_str_ExpectAnyArgsAndReturn(cmock_retval) __fwk_id_str_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void __fwk_id_str_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, struct __fwk_id_fmt cmock_to_return);
#define __fwk_id_str_ExpectAndReturn(id, cmock_retval) __fwk_id_str_CMockExpectAndReturn(__LINE__, id, cmock_retval)
void __fwk_id_str_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, union __fwk_id id, struct __fwk_id_fmt cmock_to_return);

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
