/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKFWK_NOTIFICATION_INTERNAL_H
#define _MOCKFWK_NOTIFICATION_INTERNAL_H

#include "unity.h"
#include "internal/fwk_notification.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void Mockfwk_notification_internal_Init(void);
void Mockfwk_notification_internal_Destroy(void);
void Mockfwk_notification_internal_Verify(void);




#define __fwk_notification_init_ExpectAnyArgsAndReturn(cmock_retval) __fwk_notification_init_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void __fwk_notification_init_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define __fwk_notification_init_ExpectAndReturn(notification_count, cmock_retval) __fwk_notification_init_CMockExpectAndReturn(__LINE__, notification_count, cmock_retval)
void __fwk_notification_init_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, size_t notification_count, int cmock_to_return);
#define __fwk_notification_reset_Expect() __fwk_notification_reset_CMockExpect(__LINE__)
void __fwk_notification_reset_CMockExpect(UNITY_LINE_TYPE cmock_line);

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
