/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "internal/Mockfwk_delayed_resp_internal.h"

static const char* CMockString___fwk_get_delayed_response_list = "__fwk_get_delayed_response_list";
static const char* CMockString___fwk_search_delayed_response = "__fwk_search_delayed_response";
static const char* CMockString_cookie = "cookie";
static const char* CMockString_id = "id";

typedef struct _CMOCK___fwk_get_delayed_response_list_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  struct fwk_slist* ReturnVal;
  fwk_id_t Expected_id;

} CMOCK___fwk_get_delayed_response_list_CALL_INSTANCE;

typedef struct _CMOCK___fwk_search_delayed_response_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  struct fwk_event* ReturnVal;
  fwk_id_t Expected_id;
  uint32_t Expected_cookie;

} CMOCK___fwk_search_delayed_response_CALL_INSTANCE;

static struct Mockfwk_delayed_resp_internalInstance
{
  CMOCK_MEM_INDEX_TYPE __fwk_get_delayed_response_list_CallInstance;
  CMOCK_MEM_INDEX_TYPE __fwk_search_delayed_response_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockfwk_delayed_resp_internal_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.__fwk_get_delayed_response_list_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString___fwk_get_delayed_response_list);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.__fwk_search_delayed_response_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString___fwk_search_delayed_response);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
}

void Mockfwk_delayed_resp_internal_Init(void)
{
  Mockfwk_delayed_resp_internal_Destroy();
}

void Mockfwk_delayed_resp_internal_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

struct fwk_slist* __fwk_get_delayed_response_list(fwk_id_t id)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK___fwk_get_delayed_response_list_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString___fwk_get_delayed_response_list);
  cmock_call_instance = (CMOCK___fwk_get_delayed_response_list_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.__fwk_get_delayed_response_list_CallInstance);
  Mock.__fwk_get_delayed_response_list_CallInstance = CMock_Guts_MemNext(Mock.__fwk_get_delayed_response_list_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  {
    UNITY_SET_DETAILS(CMockString___fwk_get_delayed_response_list,CMockString_id);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_id), (void*)(&id), sizeof(fwk_id_t), cmock_line, CMockStringMismatch);
  }
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters___fwk_get_delayed_response_list(CMOCK___fwk_get_delayed_response_list_CALL_INSTANCE* cmock_call_instance, fwk_id_t id);
void CMockExpectParameters___fwk_get_delayed_response_list(CMOCK___fwk_get_delayed_response_list_CALL_INSTANCE* cmock_call_instance, fwk_id_t id)
{
  memcpy((void*)(&cmock_call_instance->Expected_id), (void*)(&id),
         sizeof(fwk_id_t[sizeof(id) == sizeof(fwk_id_t) ? 1 : -1])); /* add fwk_id_t to :treat_as_array if this causes an error */
}

void __fwk_get_delayed_response_list_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, struct fwk_slist* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK___fwk_get_delayed_response_list_CALL_INSTANCE));
  CMOCK___fwk_get_delayed_response_list_CALL_INSTANCE* cmock_call_instance = (CMOCK___fwk_get_delayed_response_list_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.__fwk_get_delayed_response_list_CallInstance = CMock_Guts_MemChain(Mock.__fwk_get_delayed_response_list_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void __fwk_get_delayed_response_list_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, fwk_id_t id, struct fwk_slist* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK___fwk_get_delayed_response_list_CALL_INSTANCE));
  CMOCK___fwk_get_delayed_response_list_CALL_INSTANCE* cmock_call_instance = (CMOCK___fwk_get_delayed_response_list_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.__fwk_get_delayed_response_list_CallInstance = CMock_Guts_MemChain(Mock.__fwk_get_delayed_response_list_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters___fwk_get_delayed_response_list(cmock_call_instance, id);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

struct fwk_event* __fwk_search_delayed_response(fwk_id_t id, uint32_t cookie)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK___fwk_search_delayed_response_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString___fwk_search_delayed_response);
  cmock_call_instance = (CMOCK___fwk_search_delayed_response_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.__fwk_search_delayed_response_CallInstance);
  Mock.__fwk_search_delayed_response_CallInstance = CMock_Guts_MemNext(Mock.__fwk_search_delayed_response_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  {
    UNITY_SET_DETAILS(CMockString___fwk_search_delayed_response,CMockString_id);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_id), (void*)(&id), sizeof(fwk_id_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString___fwk_search_delayed_response,CMockString_cookie);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_cookie, cookie, cmock_line, CMockStringMismatch);
  }
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters___fwk_search_delayed_response(CMOCK___fwk_search_delayed_response_CALL_INSTANCE* cmock_call_instance, fwk_id_t id, uint32_t cookie);
void CMockExpectParameters___fwk_search_delayed_response(CMOCK___fwk_search_delayed_response_CALL_INSTANCE* cmock_call_instance, fwk_id_t id, uint32_t cookie)
{
  memcpy((void*)(&cmock_call_instance->Expected_id), (void*)(&id),
         sizeof(fwk_id_t[sizeof(id) == sizeof(fwk_id_t) ? 1 : -1])); /* add fwk_id_t to :treat_as_array if this causes an error */
  cmock_call_instance->Expected_cookie = cookie;
}

void __fwk_search_delayed_response_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, struct fwk_event* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK___fwk_search_delayed_response_CALL_INSTANCE));
  CMOCK___fwk_search_delayed_response_CALL_INSTANCE* cmock_call_instance = (CMOCK___fwk_search_delayed_response_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.__fwk_search_delayed_response_CallInstance = CMock_Guts_MemChain(Mock.__fwk_search_delayed_response_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void __fwk_search_delayed_response_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, fwk_id_t id, uint32_t cookie, struct fwk_event* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK___fwk_search_delayed_response_CALL_INSTANCE));
  CMOCK___fwk_search_delayed_response_CALL_INSTANCE* cmock_call_instance = (CMOCK___fwk_search_delayed_response_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.__fwk_search_delayed_response_CallInstance = CMock_Guts_MemChain(Mock.__fwk_search_delayed_response_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters___fwk_search_delayed_response(cmock_call_instance, id, cookie);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

