/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "internal/Mockfwk_context_internal.h"

static const char* CMockString___fwk_get_ctx = "__fwk_get_ctx";

typedef struct _CMOCK___fwk_get_ctx_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  struct __fwk_ctx* ReturnVal;

} CMOCK___fwk_get_ctx_CALL_INSTANCE;

static struct Mockfwk_context_internalInstance
{
  CMOCK_MEM_INDEX_TYPE __fwk_get_ctx_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockfwk_context_internal_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.__fwk_get_ctx_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString___fwk_get_ctx);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
}

void Mockfwk_context_internal_Init(void)
{
  Mockfwk_context_internal_Destroy();
}

void Mockfwk_context_internal_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

struct __fwk_ctx* __fwk_get_ctx(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK___fwk_get_ctx_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString___fwk_get_ctx);
  cmock_call_instance = (CMOCK___fwk_get_ctx_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.__fwk_get_ctx_CallInstance);
  Mock.__fwk_get_ctx_CallInstance = CMock_Guts_MemNext(Mock.__fwk_get_ctx_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void __fwk_get_ctx_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, struct __fwk_ctx* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK___fwk_get_ctx_CALL_INSTANCE));
  CMOCK___fwk_get_ctx_CALL_INSTANCE* cmock_call_instance = (CMOCK___fwk_get_ctx_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.__fwk_get_ctx_CallInstance = CMock_Guts_MemChain(Mock.__fwk_get_ctx_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

