/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKFWK_INTERRUPT_INTERNAL_H
#define _MOCKFWK_INTERRUPT_INTERNAL_H

#include "unity.h"
#include "internal/fwk_interrupt.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void Mockfwk_interrupt_internal_Init(void);
void Mockfwk_interrupt_internal_Destroy(void);
void Mockfwk_interrupt_internal_Verify(void);


typedef void(*cmock_fwk_interrupt_func_ptr1)(void);


#define fwk_interrupt_set_isr_fault_ExpectAnyArgsAndReturn(cmock_retval) fwk_interrupt_set_isr_fault_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void fwk_interrupt_set_isr_fault_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define fwk_interrupt_set_isr_fault_ExpectAndReturn(isr, cmock_retval) fwk_interrupt_set_isr_fault_CMockExpectAndReturn(__LINE__, isr, cmock_retval)
void fwk_interrupt_set_isr_fault_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, cmock_fwk_interrupt_func_ptr1 isr, int cmock_to_return);

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
