#
# Arm SCP/MCP Software
# Copyright (c) 2019, Arm Limited and Contributors. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

BS_LIB_NAME := Reset Domain
BS_LIB_SOURCES := mod_reset_domain.c

include $(BS_DIR)/lib.mk
