#
# Arm SCP/MCP Software
# Copyright (c) 2019-2020, Arm Limited and Contributors. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

BS_LIB_NAME := "Juno RAM"
BS_LIB_SOURCES = juno_wdog_ram.c mod_juno_ram.c

include $(BS_DIR)/lib.mk
