#
# Renesas SCP/MCP Software
# Copyright (c) 2020-2021, Renesas Electronics Corporation. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

BS_LIB_NAME := Clock HAL
BS_LIB_SOURCES := mod_rcar_clock.c

include $(BS_DIR)/lib.mk
