#
# Arm SCP/MCP Software
# Copyright (c) 2017-2019, Arm Limited and Contributors. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

BS_LIB_NAME := dvfs
BS_LIB_SOURCES := \
    mod_dvfs_domain_api.c \
    mod_dvfs_event.c \
    mod_dvfs_module.c \
    mod_dvfs_util.c \

include $(BS_DIR)/lib.mk
