#
# Arm SCP/MCP Software
# Copyright (c) 2017-2020, Arm Limited and Contributors. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

BS_LIB_NAME := PPU_V1
BS_LIB_SOURCES = ppu_v1.c mod_ppu_v1.c

include $(BS_DIR)/lib.mk
