#
# Arm SCP/MCP Software
# Copyright (c) 2021, Arm Limited and Contributors. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

BS_LIB_NAME := "Morello PCIe"
BS_LIB_SOURCES = morello_pcie.c mod_morello_pcie.c

include $(BS_DIR)/lib.mk
