#
# Arm SCP/MCP Software
# Copyright (c) 2021, Arm Limited and Contributors. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

BS_LIB_NAME := "dwt_pmi"
BS_LIB_SOURCES = mod_dwt_pmi.c

include $(BS_DIR)/lib.mk
