/*
 * Renesas SCP/MCP Software
 * Copyright (c) 2021, Renesas Electronics Corporation. All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef CONFIG_RESOURCE_PERMS_H
#define CONFIG_RESOURCE_PERMS_H

enum rcar_res_perms_devices {
    RCAR_RES_PERMS_DEVICES_CPU = 0,
    RCAR_RES_PERMS_DEVICES_ETHERAVB,
    RCAR_RES_PERMS_DEVICES_HDMI0,
    RCAR_RES_PERMS_DEVICES_HDMI1,
    RCAR_RES_PERMS_DEVICES_I2C0,
    RCAR_RES_PERMS_DEVICES_I2C1,
    RCAR_RES_PERMS_DEVICES_I2C2,
    RCAR_RES_PERMS_DEVICES_I2C3,
    RCAR_RES_PERMS_DEVICES_I2C4,
    RCAR_RES_PERMS_DEVICES_GPIO0,
    RCAR_RES_PERMS_DEVICES_GPIO1,
    RCAR_RES_PERMS_DEVICES_GPIO2,
    RCAR_RES_PERMS_DEVICES_SDHI0,
    RCAR_RES_PERMS_DEVICES_SDHI1,
    RCAR_RES_PERMS_DEVICES_SDHI2,
    RCAR_RES_PERMS_DEVICES_SDHI3,
    RCAR_RES_PERMS_DEVICES_INTC_AP,
    RCAR_RES_PERMS_DEVICES_DMAC0,
    RCAR_RES_PERMS_DEVICES_DMAC1,
    RCAR_RES_PERMS_DEVICES_DMAC2,
    RCAR_RES_PERMS_DEVICES_AUDMAC0,
    RCAR_RES_PERMS_DEVICES_AUDMAC1,
    RCAR_RES_PERMS_DEVICES_USB0,
    RCAR_RES_PERMS_DEVICES_USB1,
    RCAR_RES_PERMS_DEVICES_USB2,
    RCAR_RES_PERMS_DEVICES_USB3,
    RCAR_RES_PERMS_DEVICES_COUNT
};

#endif /* CONFIG_RESOURCE_PERMS_H */
