#
# Arm SCP/MCP Software
# Copyright (c) 2015-2020, Arm Limited and Contributors. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

BS_LIB_NAME := mod_dmc500
BS_LIB_SOURCES += mod_dmc500.c

include $(BS_DIR)/lib.mk
