#
# Arm SCP/MCP Software
# Copyright (c) 2019-2020, Arm Limited and Contributors. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

BS_LIB_NAME := N1SDP DDR PHY
BS_LIB_SOURCES += mod_n1sdp_ddr_phy.c
BS_LIB_SOURCES += ddr_phy_values_800.c ddr_phy_values_1200.c ddr_phy_values_1333.c

include $(BS_DIR)/lib.mk
