#
# Arm SCP/MCP Software
# Copyright (c) 2019, Arm Limited and Contributors. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

BS_LIB_NAME := N1SDP DDR PHY
BS_LIB_SOURCES += mod_n1sdp_ddr_phy.c

include $(BS_DIR)/lib.mk
