#
# Arm SCP/MCP Software
# Copyright (c) 2017-2019, Arm Limited and Contributors. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

BS_LIB_NAME := mock_psu
BS_LIB_SOURCES := \
    mod_mock_psu_module.c \
    mod_mock_psu_psu_driver_api.c

include $(BS_DIR)/lib.mk
