/*
 * Arm SCP/MCP Software
 * Copyright (c) 2021, Arm Limited and Contributors. All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef SCP_MMAP_H
#define SCP_MMAP_H

#define SCP_ELEMENT_MANAGEMENT_PERIPHERAL_BASE UINT32_C(0x50000000)
#define SCP_SYSTEM_ACCESS_PORT0_BASE           UINT32_C(0x60000000)

#define SCP_UART_BOARD_BASE  (SCP_SYSTEM_ACCESS_PORT0_BASE + 0x3FF70000)
#define SCP_PIK_SCP_BASE     (SCP_ELEMENT_MANAGEMENT_PERIPHERAL_BASE)
#define SCP_PIK_CLUSTER_BASE (SCP_ELEMENT_MANAGEMENT_PERIPHERAL_BASE + 0x60000)
#define SCP_PIK_SYSTEM_BASE  (SCP_ELEMENT_MANAGEMENT_PERIPHERAL_BASE + 0x40000)
#define SCP_PIK_DPU_BASE     (SCP_ELEMENT_MANAGEMENT_PERIPHERAL_BASE + 0xE0000)

#endif /* SCP_MMAP_H */
