#
# Arm SCP/MCP Software
# Copyright (c) 2018-2020, Arm Limited and Contributors. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

BS_LIB_NAME := SYNQUACER SYSTEM
BS_LIB_SOURCES = mod_synquacer_system.c \
                 sysdef_option.c \
                 synquacer_main.c \
                 load_secure_fw.c \
                 boot_ctl.c \
                 synquacer_pd_manage.c \
                 pmu_driver.c \
                 transaction_sw.c \
                 nic400.c \
                 sysoc.c \
                 mmu500.c \
                 smmu_config.c \
                 thermal_sensor.c \
                 gpio.c

include $(BS_DIR)/lib.mk
