#
# Arm SCP/MCP Software
# Copyright (c) 2018-2020, Arm Limited and Contributors. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

BS_LIB_NAME := "hsspi"
BS_LIB_SOURCES = mod_hsspi.c hsspi_api.c hsspi_driver.c

include $(BS_DIR)/lib.mk
