#
# Arm SCP/MCP Software
# Copyright (c) 2018-2022, Arm Limited and Contributors. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

BS_LIB_NAME := "hsspi"
BS_LIB_SOURCES = mod_hsspi.c

include $(BS_DIR)/lib.mk
