#
# Renesas SCP/MCP Software
# Copyright (c) 2020, Renesas Electronics Corporation. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

BS_LIB_NAME := rcar_pmic
BS_LIB_SOURCES := \
    mod_rcar_pmic_device_api.c \
    mod_rcar_pmic_event.c \
    mod_rcar_pmic_module.c

include $(BS_DIR)/lib.mk
