#
# Renesas SCP/MCP Software
# Copyright (c) 2020-2021, Renesas Electronics Corporation. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

BS_LIB_NAME := rcar_mock_pmic
BS_LIB_SOURCES := \
    mod_rcar_mock_pmic_module.c \
    mod_rcar_mock_pmic_driver_api.c

include $(BS_DIR)/lib.mk
