#
# Arm SCP/MCP Software
# Copyright (c) 2022, Arm Limited and Contributors. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

BS_LIB_NAME := TC0 POWER MODEL
BS_LIB_SOURCES = mod_tc0_power_model.c

include $(BS_DIR)/lib.mk
