#
# Renesas SCP/MCP Software
# Copyright (c) 2020, Renesas Electronics Corporation. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

BS_LIB_NAME := RCAR SYSTEM POWER
BS_LIB_SOURCES = mod_rcar_system_power.c

include $(BS_DIR)/lib.mk
