#
# Arm SCP/MCP Software
# Copyright (c) 2020, Arm Limited and Contributors. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

BS_LIB_NAME := SYSTEM INFORMATION HAL
BS_LIB_SOURCES := mod_system_info.c

include $(BS_DIR)/lib.mk
