cmake_dependent_option(
    SCP_ENABLE_FAST_CHANNELS "Enable the SCMI Fast Channels ?"
    "${SCP_ENABLE_FAST_CHANNELS_INIT}" "DEFINED SCP_ENABLE_FAST_CHANNELS_INIT"
    "${SCP_ENABLE_FAST_CHANNELS}")

cmake_dependent_option(
    SCP_ENABLE_PLUGIN_HANDLER "Enable the Performance Plugin Handler ?"
    "${SCP_ENABLE_PLUGIN_HANDLER_INIT}" "DEFINED SCP_ENABLE_PLUGIN_HANDLER_INIT"
    "${SCP_ENABLE_PLUGIN_HANDLER}")
