#
# Arm SCP/MCP Software
# Copyright (c) 2017-2020, Arm Limited and Contributors. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

BS_LIB_NAME := CSS Clock Driver
BS_LIB_SOURCES := mod_css_clock.c

include $(BS_DIR)/lib.mk
