#
# Arm SCP/MCP Software
# Copyright (c) 2015-2020, Arm Limited and Contributors. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

BS_LIB_NAME := SGM775 DDR-PHY500
BS_LIB_SOURCES += mod_sgm775_ddr_phy500.c

include $(BS_DIR)/lib.mk
