#
# Arm SCP/MCP Software
# Copyright (c) 2017-2020, Arm Limited and Contributors. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

BS_LIB_NAME := Bootloader
BS_LIB_SOURCES := \
    mod_bootloader.c \
    mod_bootloader_boot.S

include $(BS_DIR)/lib.mk
