#
# Arm SCP/MCP Software
# Copyright (c) 2015-2020, Arm Limited and Contributors. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

BS_LIB_NAME := "DW APB I2C"
BS_LIB_SOURCES = mod_dw_apb_i2c.c

include $(BS_DIR)/lib.mk
