#
# Arm SCP/MCP Software
# Copyright (c) 2020, Arm Limited and Contributors. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

BS_LIB_NAME := CMN_BOOKER

BS_LIB_SOURCES = mod_cmn_booker.c
BS_LIB_SOURCES += cmn_booker.c

include $(BS_DIR)/lib.mk
