#
# Arm SCP/MCP Software
# Copyright (c) 2021, Arm Limited and Contributors. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

BS_LIB_NAME := N1SDP Sensor
BS_LIB_SOURCES := mod_n1sdp_sensor.c

include $(BS_DIR)/lib.mk
