#
# Renesas SCP/MCP Software
# Copyright (c) 2020-2021, Renesas Electronics Corporation. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

BS_LIB_NAME := RCAR_ARCH_TIMER
BS_LIB_SOURCES = mod_rcar_arch_timer.c

include $(BS_DIR)/lib.mk
