#
# Renesas SCP/MCP Software
# Copyright (c) 2020, Renesas Electronics Corporation. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

BS_LIB_NAME := Power domain
BS_LIB_SOURCES := mod_rcar_power_domain.c

include $(BS_DIR)/lib.mk
