#
# Arm SCP/MCP Software
# Copyright (c) 2024, Arm Limited and Contributors. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

stages:
  - test-workspace
  - linting
  - static-analysis
  - unit-testing
  - build
  - scmi-test

include:
  - local: .gitlab/templates/setup-workspace.yml
  - local: .gitlab/templates/status-report.yml
  - local: .gitlab/templates/linting.yml
  - local: .gitlab/templates/static-analysis.yml
  - local: .gitlab/templates/unit-test.yml
  - local: .gitlab/templates/build-test.yml
  - local: .gitlab/templates/scmi-test.yml
  - local: .gitlab/templates/coverity-test.yml


pull-mr:
  stage: .pre
  extends: .pull-mr

report-pipeline-start:
  stage: .pre
  extends: .report-pipeline-start

report-pipeline-success:
  stage: .post
  extends: .report-pipeline-success

report-pipeline-failure:
 stage: .post
 extends: .report-pipeline-failure

check-lint:
  extends:
    - .check-lint
    - .git-strategy-on-mr
  stage: linting
  dependencies:
    - pull-mr

check-copyright:
  before_script:
    - ls .gitlab/templates
  extends:
    - .check-copyright
    - .git-strategy-on-mr
  stage: linting
  dependencies:
    - pull-mr

check-style:
  extends:
    - .check-style
    - .git-strategy-on-mr
  stage: linting
  dependencies:
    - pull-mr

banned-api:
  extends:
    - .banned-api
    - .git-strategy-on-mr
  stage: static-analysis
  dependencies:
    - pull-mr

coverity-test:
  stage: static-analysis
  extends:
    - .coverity-test
    - .git-strategy-on-mr
  dependencies:
    - pull-mr

check-ut:
  extends:
    - .check-ut
    - .git-strategy-on-mr
  stage: unit-testing
  dependencies:
    - pull-mr

build-products:
  extends:
    - .build-products
    - .git-strategy-on-mr
  stage: build
  dependencies:
    - pull-mr

scmi-test:
  extends:
    - .scmi-test
    - .git-strategy-on-mr
  stage: scmi-test
  dependencies:
    - pull-mr
