#
# Arm SCP/MCP Software
# Copyright (c) 2024, Arm Limited and Contributors. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

stages:
  - test-workspace
  - linting
  - static-analysis
  - unit-testing
  - build
  - scmi-test
  - platform-test
  - coverage-report

include:
  - local: .gitlab/templates/setup-workspace.yml
  - local: .gitlab/templates/status-report.yml
  - local: .gitlab/templates/linting.yml
  - local: .gitlab/templates/static-analysis.yml
  - local: .gitlab/templates/unit-test.yml
  - local: .gitlab/templates/build-test.yml
  - local: .gitlab/templates/scmi-test.yml
  - local: .gitlab/templates/coverity-test.yml
  - local: .gitlab/templates/platform-test.yml
  - local: .gitlab/templates/merge-report.yml

pull-mr:
  stage: .pre
  extends: .pull-mr

report-pipeline-start:
  stage: .pre
  extends: .report-pipeline-start

report-pipeline-success:
  stage: .post
  extends: .report-pipeline-success

report-pipeline-failure:
 stage: .post
 extends: .report-pipeline-failure

check-lint:
  extends:
    - .check-lint
    - .git-strategy-on-mr
  stage: linting
  dependencies:
    - pull-mr

check-copyright:
  extends:
    - .check-copyright
    - .git-strategy-on-mr
  stage: linting
  dependencies:
    - pull-mr

check-style:
  extends:
    - .check-style
    - .git-strategy-on-mr
  stage: linting
  dependencies:
    - pull-mr

check-for-merge-commits:
  extends:
    - .check-for-merge-commits
    - .git-strategy-on-mr
  stage: linting
  dependencies:
    - pull-mr

banned-api:
  extends:
    - .banned-api
    - .git-strategy-on-mr
  stage: static-analysis
  dependencies:
    - pull-mr

coverity-test:
  stage: static-analysis
  extends:
    - .coverity-test
    - .git-strategy-on-mr
  dependencies:
    - pull-mr

check-ut:
  extends:
    - .check-ut
    - .git-strategy-on-mr
  stage: unit-testing
  dependencies:
    - pull-mr

build-products:
  extends:
    - .build-products-all-products
    - .git-strategy-on-mr
  stage: build
  dependencies:
    - pull-mr

build-optee:
  extends:
    - .build-optee
    - .git-strategy-on-mr
  stage: build
  dependencies:
    - pull-mr

scmi-test:
  extends:
    - .scmi-test
    - .git-strategy-on-mr
  stage: scmi-test
  dependencies:
    - pull-mr

fvp-boot-test:
  extends:
    - .fvp-boot-test
    - .git-strategy-on-mr
    - .auto_on_public_mr_only
  stage: platform-test

board-test-build:
  extends:
    - .board-test-build
    - .git-strategy-on-mr
    - .auto_on_public_mr_only
  stage: platform-test

board-test-run:
  extends:
    - .board-test-run
    - .git-strategy-on-mr
    - .auto_on_public_mr_only
  stage: platform-test
  needs:
    - board-test-build

merge-ut-coverage:
  extends:
    - .merge-report
    - .git-strategy-on-mr
  stage: coverage-report
  dependencies:
    - pull-mr
    - check-ut
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: artifacts/coverage_reports/merge_report/merge_coverage.xml

merge-all-coverage:
  extends:
    - .merge-report
    - .git-strategy-on-mr
  stage: coverage-report
  # Example of 'coverage' regex matches in coverage report
  # "lines......: XX.X% (XXXX of XXXX lines)"
  coverage: '/lines[\.]+\: (\d+\.\d+)\%/'
  dependencies:
    - pull-mr
    - check-ut
    - scmi-test
    - fvp-boot-test
