#
# Arm SCP/MCP Software
# Copyright (c) 2017-2020, Arm Limited and Contributors. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

BS_LIB_NAME := RDN1E1 SYSTEM
BS_LIB_SOURCES = mod_rdn1e1_system.c

include $(BS_DIR)/lib.mk
