/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mockmod_power_allocator_extra.h"

static const char* CMockString_cap = "cap";
static const char* CMockString_domain_id = "domain_id";
static const char* CMockString_get_cap = "get_cap";
static const char* CMockString_set_cap = "set_cap";

typedef struct _CMOCK_get_cap_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int ReturnVal;
  fwk_id_t Expected_domain_id;
  uint32_t* Expected_cap;
  int Expected_cap_Depth;
  char ReturnThruPtr_cap_Used;
  uint32_t* ReturnThruPtr_cap_Val;
  size_t ReturnThruPtr_cap_Size;
  char IgnoreArg_domain_id;
  char IgnoreArg_cap;

} CMOCK_get_cap_CALL_INSTANCE;

typedef struct _CMOCK_set_cap_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int ReturnVal;
  fwk_id_t Expected_domain_id;
  uint32_t Expected_cap;
  char IgnoreArg_domain_id;
  char IgnoreArg_cap;

} CMOCK_set_cap_CALL_INSTANCE;

static struct Mockmod_power_allocator_extraInstance
{
  char get_cap_IgnoreBool;
  int get_cap_FinalReturn;
  char get_cap_CallbackBool;
  CMOCK_get_cap_CALLBACK get_cap_CallbackFunctionPointer;
  int get_cap_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE get_cap_CallInstance;
  char set_cap_IgnoreBool;
  int set_cap_FinalReturn;
  char set_cap_CallbackBool;
  CMOCK_set_cap_CALLBACK set_cap_CallbackFunctionPointer;
  int set_cap_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE set_cap_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockmod_power_allocator_extra_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.get_cap_CallInstance;
  if (Mock.get_cap_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_get_cap);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.get_cap_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.set_cap_CallInstance;
  if (Mock.set_cap_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_set_cap);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.set_cap_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void Mockmod_power_allocator_extra_Init(void)
{
  Mockmod_power_allocator_extra_Destroy();
}

void Mockmod_power_allocator_extra_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

int get_cap(fwk_id_t domain_id, uint32_t* cap)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_get_cap_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_get_cap);
  cmock_call_instance = (CMOCK_get_cap_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.get_cap_CallInstance);
  Mock.get_cap_CallInstance = CMock_Guts_MemNext(Mock.get_cap_CallInstance);
  if (Mock.get_cap_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.get_cap_FinalReturn;
    Mock.get_cap_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.get_cap_CallbackBool &&
      Mock.get_cap_CallbackFunctionPointer != NULL)
  {
    int cmock_cb_ret = Mock.get_cap_CallbackFunctionPointer(domain_id, cap, Mock.get_cap_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_domain_id)
  {
    UNITY_SET_DETAILS(CMockString_get_cap,CMockString_domain_id);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_domain_id), (void*)(&domain_id), sizeof(fwk_id_t), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_cap)
  {
    UNITY_SET_DETAILS(CMockString_get_cap,CMockString_cap);
    if (cmock_call_instance->Expected_cap == NULL)
      { UNITY_TEST_ASSERT_NULL(cap, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX32_ARRAY(cmock_call_instance->Expected_cap, cap, cmock_call_instance->Expected_cap_Depth, cmock_line, CMockStringMismatch); }
  }
  }
  if (Mock.get_cap_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.get_cap_CallbackFunctionPointer(domain_id, cap, Mock.get_cap_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_cap_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(cap, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)cap, (void*)cmock_call_instance->ReturnThruPtr_cap_Val,
      cmock_call_instance->ReturnThruPtr_cap_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_get_cap(CMOCK_get_cap_CALL_INSTANCE* cmock_call_instance, fwk_id_t domain_id, uint32_t* cap, int cap_Depth);
void CMockExpectParameters_get_cap(CMOCK_get_cap_CALL_INSTANCE* cmock_call_instance, fwk_id_t domain_id, uint32_t* cap, int cap_Depth)
{
  memcpy((void*)(&cmock_call_instance->Expected_domain_id), (void*)(&domain_id),
         sizeof(fwk_id_t[sizeof(domain_id) == sizeof(fwk_id_t) ? 1 : -1])); /* add fwk_id_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_domain_id = 0;
  cmock_call_instance->Expected_cap = cap;
  cmock_call_instance->Expected_cap_Depth = cap_Depth;
  cmock_call_instance->IgnoreArg_cap = 0;
  cmock_call_instance->ReturnThruPtr_cap_Used = 0;
}

void get_cap_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_get_cap_CALL_INSTANCE));
  CMOCK_get_cap_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_cap_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.get_cap_CallInstance = CMock_Guts_MemChain(Mock.get_cap_CallInstance, cmock_guts_index);
  Mock.get_cap_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.get_cap_IgnoreBool = (char)1;
}

void get_cap_CMockStopIgnore(void)
{
  if(Mock.get_cap_IgnoreBool)
    Mock.get_cap_CallInstance = CMock_Guts_MemNext(Mock.get_cap_CallInstance);
  Mock.get_cap_IgnoreBool = (char)0;
}

void get_cap_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_get_cap_CALL_INSTANCE));
  CMOCK_get_cap_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_cap_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.get_cap_CallInstance = CMock_Guts_MemChain(Mock.get_cap_CallInstance, cmock_guts_index);
  Mock.get_cap_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void get_cap_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, fwk_id_t domain_id, uint32_t* cap, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_get_cap_CALL_INSTANCE));
  CMOCK_get_cap_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_cap_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.get_cap_CallInstance = CMock_Guts_MemChain(Mock.get_cap_CallInstance, cmock_guts_index);
  Mock.get_cap_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_get_cap(cmock_call_instance, domain_id, cap, 1);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void get_cap_AddCallback(CMOCK_get_cap_CALLBACK Callback)
{
  Mock.get_cap_IgnoreBool = (char)0;
  Mock.get_cap_CallbackBool = (char)1;
  Mock.get_cap_CallbackFunctionPointer = Callback;
}

void get_cap_Stub(CMOCK_get_cap_CALLBACK Callback)
{
  Mock.get_cap_IgnoreBool = (char)0;
  Mock.get_cap_CallbackBool = (char)0;
  Mock.get_cap_CallbackFunctionPointer = Callback;
}

void get_cap_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, fwk_id_t domain_id, uint32_t* cap, int cap_Depth, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_get_cap_CALL_INSTANCE));
  CMOCK_get_cap_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_cap_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.get_cap_CallInstance = CMock_Guts_MemChain(Mock.get_cap_CallInstance, cmock_guts_index);
  Mock.get_cap_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_get_cap(cmock_call_instance, domain_id, cap, cap_Depth);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void get_cap_CMockReturnMemThruPtr_cap(UNITY_LINE_TYPE cmock_line, uint32_t* cap, size_t cmock_size)
{
  CMOCK_get_cap_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_cap_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.get_cap_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_cap_Used = 1;
  cmock_call_instance->ReturnThruPtr_cap_Val = cap;
  cmock_call_instance->ReturnThruPtr_cap_Size = cmock_size;
}

void get_cap_CMockIgnoreArg_domain_id(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_get_cap_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_cap_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.get_cap_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_domain_id = 1;
}

void get_cap_CMockIgnoreArg_cap(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_get_cap_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_cap_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.get_cap_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_cap = 1;
}

int set_cap(fwk_id_t domain_id, uint32_t cap)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_set_cap_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_set_cap);
  cmock_call_instance = (CMOCK_set_cap_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.set_cap_CallInstance);
  Mock.set_cap_CallInstance = CMock_Guts_MemNext(Mock.set_cap_CallInstance);
  if (Mock.set_cap_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.set_cap_FinalReturn;
    Mock.set_cap_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.set_cap_CallbackBool &&
      Mock.set_cap_CallbackFunctionPointer != NULL)
  {
    int cmock_cb_ret = Mock.set_cap_CallbackFunctionPointer(domain_id, cap, Mock.set_cap_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_domain_id)
  {
    UNITY_SET_DETAILS(CMockString_set_cap,CMockString_domain_id);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_domain_id), (void*)(&domain_id), sizeof(fwk_id_t), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_cap)
  {
    UNITY_SET_DETAILS(CMockString_set_cap,CMockString_cap);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_cap, cap, cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.set_cap_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.set_cap_CallbackFunctionPointer(domain_id, cap, Mock.set_cap_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_set_cap(CMOCK_set_cap_CALL_INSTANCE* cmock_call_instance, fwk_id_t domain_id, uint32_t cap);
void CMockExpectParameters_set_cap(CMOCK_set_cap_CALL_INSTANCE* cmock_call_instance, fwk_id_t domain_id, uint32_t cap)
{
  memcpy((void*)(&cmock_call_instance->Expected_domain_id), (void*)(&domain_id),
         sizeof(fwk_id_t[sizeof(domain_id) == sizeof(fwk_id_t) ? 1 : -1])); /* add fwk_id_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_domain_id = 0;
  cmock_call_instance->Expected_cap = cap;
  cmock_call_instance->IgnoreArg_cap = 0;
}

void set_cap_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_set_cap_CALL_INSTANCE));
  CMOCK_set_cap_CALL_INSTANCE* cmock_call_instance = (CMOCK_set_cap_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.set_cap_CallInstance = CMock_Guts_MemChain(Mock.set_cap_CallInstance, cmock_guts_index);
  Mock.set_cap_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.set_cap_IgnoreBool = (char)1;
}

void set_cap_CMockStopIgnore(void)
{
  if(Mock.set_cap_IgnoreBool)
    Mock.set_cap_CallInstance = CMock_Guts_MemNext(Mock.set_cap_CallInstance);
  Mock.set_cap_IgnoreBool = (char)0;
}

void set_cap_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_set_cap_CALL_INSTANCE));
  CMOCK_set_cap_CALL_INSTANCE* cmock_call_instance = (CMOCK_set_cap_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.set_cap_CallInstance = CMock_Guts_MemChain(Mock.set_cap_CallInstance, cmock_guts_index);
  Mock.set_cap_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void set_cap_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, fwk_id_t domain_id, uint32_t cap, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_set_cap_CALL_INSTANCE));
  CMOCK_set_cap_CALL_INSTANCE* cmock_call_instance = (CMOCK_set_cap_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.set_cap_CallInstance = CMock_Guts_MemChain(Mock.set_cap_CallInstance, cmock_guts_index);
  Mock.set_cap_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_set_cap(cmock_call_instance, domain_id, cap);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void set_cap_AddCallback(CMOCK_set_cap_CALLBACK Callback)
{
  Mock.set_cap_IgnoreBool = (char)0;
  Mock.set_cap_CallbackBool = (char)1;
  Mock.set_cap_CallbackFunctionPointer = Callback;
}

void set_cap_Stub(CMOCK_set_cap_CALLBACK Callback)
{
  Mock.set_cap_IgnoreBool = (char)0;
  Mock.set_cap_CallbackBool = (char)0;
  Mock.set_cap_CallbackFunctionPointer = Callback;
}

void set_cap_CMockIgnoreArg_domain_id(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_set_cap_CALL_INSTANCE* cmock_call_instance = (CMOCK_set_cap_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.set_cap_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_domain_id = 1;
}

void set_cap_CMockIgnoreArg_cap(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_set_cap_CALL_INSTANCE* cmock_call_instance = (CMOCK_set_cap_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.set_cap_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_cap = 1;
}

