/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mockmod_power_meter_extra.h"

static const char* CMockString_domain_id = "domain_id";
static const char* CMockString_get_power = "get_power";
static const char* CMockString_power = "power";

typedef struct _CMOCK_get_power_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int ReturnVal;
  fwk_id_t Expected_domain_id;
  uint32_t* Expected_power;
  int Expected_power_Depth;
  char ReturnThruPtr_power_Used;
  uint32_t* ReturnThruPtr_power_Val;
  size_t ReturnThruPtr_power_Size;
  char IgnoreArg_domain_id;
  char IgnoreArg_power;

} CMOCK_get_power_CALL_INSTANCE;

static struct Mockmod_power_meter_extraInstance
{
  char get_power_IgnoreBool;
  int get_power_FinalReturn;
  char get_power_CallbackBool;
  CMOCK_get_power_CALLBACK get_power_CallbackFunctionPointer;
  int get_power_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE get_power_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockmod_power_meter_extra_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.get_power_CallInstance;
  if (Mock.get_power_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_get_power);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.get_power_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void Mockmod_power_meter_extra_Init(void)
{
  Mockmod_power_meter_extra_Destroy();
}

void Mockmod_power_meter_extra_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

int get_power(fwk_id_t domain_id, uint32_t* power)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_get_power_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_get_power);
  cmock_call_instance = (CMOCK_get_power_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.get_power_CallInstance);
  Mock.get_power_CallInstance = CMock_Guts_MemNext(Mock.get_power_CallInstance);
  if (Mock.get_power_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.get_power_FinalReturn;
    Mock.get_power_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.get_power_CallbackBool &&
      Mock.get_power_CallbackFunctionPointer != NULL)
  {
    int cmock_cb_ret = Mock.get_power_CallbackFunctionPointer(domain_id, power, Mock.get_power_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_domain_id)
  {
    UNITY_SET_DETAILS(CMockString_get_power,CMockString_domain_id);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_domain_id), (void*)(&domain_id), sizeof(fwk_id_t), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_power)
  {
    UNITY_SET_DETAILS(CMockString_get_power,CMockString_power);
    if (cmock_call_instance->Expected_power == NULL)
      { UNITY_TEST_ASSERT_NULL(power, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX32_ARRAY(cmock_call_instance->Expected_power, power, cmock_call_instance->Expected_power_Depth, cmock_line, CMockStringMismatch); }
  }
  }
  if (Mock.get_power_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.get_power_CallbackFunctionPointer(domain_id, power, Mock.get_power_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_power_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(power, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)power, (void*)cmock_call_instance->ReturnThruPtr_power_Val,
      cmock_call_instance->ReturnThruPtr_power_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_get_power(CMOCK_get_power_CALL_INSTANCE* cmock_call_instance, fwk_id_t domain_id, uint32_t* power, int power_Depth);
void CMockExpectParameters_get_power(CMOCK_get_power_CALL_INSTANCE* cmock_call_instance, fwk_id_t domain_id, uint32_t* power, int power_Depth)
{
  memcpy((void*)(&cmock_call_instance->Expected_domain_id), (void*)(&domain_id),
         sizeof(fwk_id_t[sizeof(domain_id) == sizeof(fwk_id_t) ? 1 : -1])); /* add fwk_id_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_domain_id = 0;
  cmock_call_instance->Expected_power = power;
  cmock_call_instance->Expected_power_Depth = power_Depth;
  cmock_call_instance->IgnoreArg_power = 0;
  cmock_call_instance->ReturnThruPtr_power_Used = 0;
}

void get_power_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_get_power_CALL_INSTANCE));
  CMOCK_get_power_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_power_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.get_power_CallInstance = CMock_Guts_MemChain(Mock.get_power_CallInstance, cmock_guts_index);
  Mock.get_power_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.get_power_IgnoreBool = (char)1;
}

void get_power_CMockStopIgnore(void)
{
  if(Mock.get_power_IgnoreBool)
    Mock.get_power_CallInstance = CMock_Guts_MemNext(Mock.get_power_CallInstance);
  Mock.get_power_IgnoreBool = (char)0;
}

void get_power_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_get_power_CALL_INSTANCE));
  CMOCK_get_power_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_power_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.get_power_CallInstance = CMock_Guts_MemChain(Mock.get_power_CallInstance, cmock_guts_index);
  Mock.get_power_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void get_power_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, fwk_id_t domain_id, uint32_t* power, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_get_power_CALL_INSTANCE));
  CMOCK_get_power_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_power_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.get_power_CallInstance = CMock_Guts_MemChain(Mock.get_power_CallInstance, cmock_guts_index);
  Mock.get_power_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_get_power(cmock_call_instance, domain_id, power, 1);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void get_power_AddCallback(CMOCK_get_power_CALLBACK Callback)
{
  Mock.get_power_IgnoreBool = (char)0;
  Mock.get_power_CallbackBool = (char)1;
  Mock.get_power_CallbackFunctionPointer = Callback;
}

void get_power_Stub(CMOCK_get_power_CALLBACK Callback)
{
  Mock.get_power_IgnoreBool = (char)0;
  Mock.get_power_CallbackBool = (char)0;
  Mock.get_power_CallbackFunctionPointer = Callback;
}

void get_power_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, fwk_id_t domain_id, uint32_t* power, int power_Depth, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_get_power_CALL_INSTANCE));
  CMOCK_get_power_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_power_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.get_power_CallInstance = CMock_Guts_MemChain(Mock.get_power_CallInstance, cmock_guts_index);
  Mock.get_power_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_get_power(cmock_call_instance, domain_id, power, power_Depth);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void get_power_CMockReturnMemThruPtr_power(UNITY_LINE_TYPE cmock_line, uint32_t* power, size_t cmock_size)
{
  CMOCK_get_power_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_power_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.get_power_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_power_Used = 1;
  cmock_call_instance->ReturnThruPtr_power_Val = power;
  cmock_call_instance->ReturnThruPtr_power_Size = cmock_size;
}

void get_power_CMockIgnoreArg_domain_id(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_get_power_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_power_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.get_power_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_domain_id = 1;
}

void get_power_CMockIgnoreArg_power(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_get_power_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_power_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.get_power_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_power = 1;
}

