/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKMOD_POWER_COORDINATOR_EXTRA_H
#define _MOCKMOD_POWER_COORDINATOR_EXTRA_H

#include "unity.h"
#include "mod_power_coordinator_extra.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void Mockmod_power_coordinator_extra_Init(void);
void Mockmod_power_coordinator_extra_Destroy(void);
void Mockmod_power_coordinator_extra_Verify(void);




#define get_coordinator_period_IgnoreAndReturn(cmock_retval) get_coordinator_period_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void get_coordinator_period_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define get_coordinator_period_StopIgnore() get_coordinator_period_CMockStopIgnore()
void get_coordinator_period_CMockStopIgnore(void);
#define get_coordinator_period_ExpectAnyArgsAndReturn(cmock_retval) get_coordinator_period_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void get_coordinator_period_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define get_coordinator_period_ExpectAndReturn(domain_id, period, cmock_retval) get_coordinator_period_CMockExpectAndReturn(__LINE__, domain_id, period, cmock_retval)
void get_coordinator_period_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, fwk_id_t domain_id, uint32_t* period, int cmock_to_return);
typedef int (* CMOCK_get_coordinator_period_CALLBACK)(fwk_id_t domain_id, uint32_t* period, int cmock_num_calls);
void get_coordinator_period_AddCallback(CMOCK_get_coordinator_period_CALLBACK Callback);
void get_coordinator_period_Stub(CMOCK_get_coordinator_period_CALLBACK Callback);
#define get_coordinator_period_StubWithCallback get_coordinator_period_Stub
#define get_coordinator_period_ExpectWithArrayAndReturn(domain_id, period, period_Depth, cmock_retval) get_coordinator_period_CMockExpectWithArrayAndReturn(__LINE__, domain_id, period, period_Depth, cmock_retval)
void get_coordinator_period_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, fwk_id_t domain_id, uint32_t* period, int period_Depth, int cmock_to_return);
#define get_coordinator_period_ReturnThruPtr_period(period) get_coordinator_period_CMockReturnMemThruPtr_period(__LINE__, period, sizeof(uint32_t))
#define get_coordinator_period_ReturnArrayThruPtr_period(period, cmock_len) get_coordinator_period_CMockReturnMemThruPtr_period(__LINE__, period, cmock_len * sizeof(*period))
#define get_coordinator_period_ReturnMemThruPtr_period(period, cmock_size) get_coordinator_period_CMockReturnMemThruPtr_period(__LINE__, period, cmock_size)
void get_coordinator_period_CMockReturnMemThruPtr_period(UNITY_LINE_TYPE cmock_line, uint32_t* period, size_t cmock_size);
#define get_coordinator_period_IgnoreArg_domain_id() get_coordinator_period_CMockIgnoreArg_domain_id(__LINE__)
void get_coordinator_period_CMockIgnoreArg_domain_id(UNITY_LINE_TYPE cmock_line);
#define get_coordinator_period_IgnoreArg_period() get_coordinator_period_CMockIgnoreArg_period(__LINE__)
void get_coordinator_period_CMockIgnoreArg_period(UNITY_LINE_TYPE cmock_line);
#define set_coordinator_period_IgnoreAndReturn(cmock_retval) set_coordinator_period_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void set_coordinator_period_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define set_coordinator_period_StopIgnore() set_coordinator_period_CMockStopIgnore()
void set_coordinator_period_CMockStopIgnore(void);
#define set_coordinator_period_ExpectAnyArgsAndReturn(cmock_retval) set_coordinator_period_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void set_coordinator_period_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define set_coordinator_period_ExpectAndReturn(domain_id, period, cmock_retval) set_coordinator_period_CMockExpectAndReturn(__LINE__, domain_id, period, cmock_retval)
void set_coordinator_period_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, fwk_id_t domain_id, uint32_t period, int cmock_to_return);
typedef int (* CMOCK_set_coordinator_period_CALLBACK)(fwk_id_t domain_id, uint32_t period, int cmock_num_calls);
void set_coordinator_period_AddCallback(CMOCK_set_coordinator_period_CALLBACK Callback);
void set_coordinator_period_Stub(CMOCK_set_coordinator_period_CALLBACK Callback);
#define set_coordinator_period_StubWithCallback set_coordinator_period_Stub
#define set_coordinator_period_IgnoreArg_domain_id() set_coordinator_period_CMockIgnoreArg_domain_id(__LINE__)
void set_coordinator_period_CMockIgnoreArg_domain_id(UNITY_LINE_TYPE cmock_line);
#define set_coordinator_period_IgnoreArg_period() set_coordinator_period_CMockIgnoreArg_period(__LINE__)
void set_coordinator_period_CMockIgnoreArg_period(UNITY_LINE_TYPE cmock_line);

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
