/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKMOD_SCMI_EXTRA_H
#define _MOCKMOD_SCMI_EXTRA_H

#include "unity.h"
#include "mod_scmi_extra.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void Mockmod_scmi_extra_Init(void);
void Mockmod_scmi_extra_Destroy(void);
void Mockmod_scmi_extra_Verify(void);




#define get_agent_count_IgnoreAndReturn(cmock_retval) get_agent_count_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void get_agent_count_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define get_agent_count_StopIgnore() get_agent_count_CMockStopIgnore()
void get_agent_count_CMockStopIgnore(void);
#define get_agent_count_ExpectAnyArgsAndReturn(cmock_retval) get_agent_count_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void get_agent_count_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define get_agent_count_ExpectAndReturn(agent_count, cmock_retval) get_agent_count_CMockExpectAndReturn(__LINE__, agent_count, cmock_retval)
void get_agent_count_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, unsigned int* agent_count, int cmock_to_return);
typedef int (* CMOCK_get_agent_count_CALLBACK)(unsigned int* agent_count, int cmock_num_calls);
void get_agent_count_AddCallback(CMOCK_get_agent_count_CALLBACK Callback);
void get_agent_count_Stub(CMOCK_get_agent_count_CALLBACK Callback);
#define get_agent_count_StubWithCallback get_agent_count_Stub
#define get_agent_count_ExpectWithArrayAndReturn(agent_count, agent_count_Depth, cmock_retval) get_agent_count_CMockExpectWithArrayAndReturn(__LINE__, agent_count, agent_count_Depth, cmock_retval)
void get_agent_count_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, unsigned int* agent_count, int agent_count_Depth, int cmock_to_return);
#define get_agent_count_ReturnThruPtr_agent_count(agent_count) get_agent_count_CMockReturnMemThruPtr_agent_count(__LINE__, agent_count, sizeof(unsigned int))
#define get_agent_count_ReturnArrayThruPtr_agent_count(agent_count, cmock_len) get_agent_count_CMockReturnMemThruPtr_agent_count(__LINE__, agent_count, cmock_len * sizeof(*agent_count))
#define get_agent_count_ReturnMemThruPtr_agent_count(agent_count, cmock_size) get_agent_count_CMockReturnMemThruPtr_agent_count(__LINE__, agent_count, cmock_size)
void get_agent_count_CMockReturnMemThruPtr_agent_count(UNITY_LINE_TYPE cmock_line, unsigned int* agent_count, size_t cmock_size);
#define get_agent_count_IgnoreArg_agent_count() get_agent_count_CMockIgnoreArg_agent_count(__LINE__)
void get_agent_count_CMockIgnoreArg_agent_count(UNITY_LINE_TYPE cmock_line);
#define get_agent_id_IgnoreAndReturn(cmock_retval) get_agent_id_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void get_agent_id_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define get_agent_id_StopIgnore() get_agent_id_CMockStopIgnore()
void get_agent_id_CMockStopIgnore(void);
#define get_agent_id_ExpectAnyArgsAndReturn(cmock_retval) get_agent_id_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void get_agent_id_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define get_agent_id_ExpectAndReturn(service_id, agent_id, cmock_retval) get_agent_id_CMockExpectAndReturn(__LINE__, service_id, agent_id, cmock_retval)
void get_agent_id_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, fwk_id_t service_id, unsigned int* agent_id, int cmock_to_return);
typedef int (* CMOCK_get_agent_id_CALLBACK)(fwk_id_t service_id, unsigned int* agent_id, int cmock_num_calls);
void get_agent_id_AddCallback(CMOCK_get_agent_id_CALLBACK Callback);
void get_agent_id_Stub(CMOCK_get_agent_id_CALLBACK Callback);
#define get_agent_id_StubWithCallback get_agent_id_Stub
#define get_agent_id_ExpectWithArrayAndReturn(service_id, agent_id, agent_id_Depth, cmock_retval) get_agent_id_CMockExpectWithArrayAndReturn(__LINE__, service_id, agent_id, agent_id_Depth, cmock_retval)
void get_agent_id_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, fwk_id_t service_id, unsigned int* agent_id, int agent_id_Depth, int cmock_to_return);
#define get_agent_id_ReturnThruPtr_agent_id(agent_id) get_agent_id_CMockReturnMemThruPtr_agent_id(__LINE__, agent_id, sizeof(unsigned int))
#define get_agent_id_ReturnArrayThruPtr_agent_id(agent_id, cmock_len) get_agent_id_CMockReturnMemThruPtr_agent_id(__LINE__, agent_id, cmock_len * sizeof(*agent_id))
#define get_agent_id_ReturnMemThruPtr_agent_id(agent_id, cmock_size) get_agent_id_CMockReturnMemThruPtr_agent_id(__LINE__, agent_id, cmock_size)
void get_agent_id_CMockReturnMemThruPtr_agent_id(UNITY_LINE_TYPE cmock_line, unsigned int* agent_id, size_t cmock_size);
#define get_agent_id_IgnoreArg_service_id() get_agent_id_CMockIgnoreArg_service_id(__LINE__)
void get_agent_id_CMockIgnoreArg_service_id(UNITY_LINE_TYPE cmock_line);
#define get_agent_id_IgnoreArg_agent_id() get_agent_id_CMockIgnoreArg_agent_id(__LINE__)
void get_agent_id_CMockIgnoreArg_agent_id(UNITY_LINE_TYPE cmock_line);
#define respond_IgnoreAndReturn(cmock_retval) respond_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void respond_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define respond_StopIgnore() respond_CMockStopIgnore()
void respond_CMockStopIgnore(void);
#define respond_ExpectAnyArgsAndReturn(cmock_retval) respond_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void respond_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define respond_ExpectAndReturn(service_id, payload, size, cmock_retval) respond_CMockExpectAndReturn(__LINE__, service_id, payload, size, cmock_retval)
void respond_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, fwk_id_t service_id, const void* payload, size_t size, int cmock_to_return);
typedef int (* CMOCK_respond_CALLBACK)(fwk_id_t service_id, const void* payload, size_t size, int cmock_num_calls);
void respond_AddCallback(CMOCK_respond_CALLBACK Callback);
void respond_Stub(CMOCK_respond_CALLBACK Callback);
#define respond_StubWithCallback respond_Stub
#define respond_ExpectWithArrayAndReturn(service_id, payload, payload_Depth, size, cmock_retval) respond_CMockExpectWithArrayAndReturn(__LINE__, service_id, payload, payload_Depth, size, cmock_retval)
void respond_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, fwk_id_t service_id, const void* payload, int payload_Depth, size_t size, int cmock_to_return);
#define respond_IgnoreArg_service_id() respond_CMockIgnoreArg_service_id(__LINE__)
void respond_CMockIgnoreArg_service_id(UNITY_LINE_TYPE cmock_line);
#define respond_IgnoreArg_payload() respond_CMockIgnoreArg_payload(__LINE__)
void respond_CMockIgnoreArg_payload(UNITY_LINE_TYPE cmock_line);
#define respond_IgnoreArg_size() respond_CMockIgnoreArg_size(__LINE__)
void respond_CMockIgnoreArg_size(UNITY_LINE_TYPE cmock_line);

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
