#
# Renesas SCP/MCP Software
# Copyright (c) 2020, Renesas Electronics Corporation. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

BS_LIB_NAME := RCAR_PS_SYSC
BS_LIB_SOURCES = rcar_pd_sysc.c mod_rcar_pd_sysc.c

include $(BS_DIR)/lib.mk
