#
# Arm SCP/MCP Software
# Copyright (c) 2020-2021, Arm Limited and Contributors. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

BS_LIB_NAME := CMN650

BS_LIB_SOURCES = mod_cmn650.c
BS_LIB_SOURCES += cmn650.c cmn650_ccix.c

include $(BS_DIR)/lib.mk
