/*
 * Arm SCP/MCP Software
 * Copyright (c) 2017-2021, Arm Limited and Contributors. All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef CONFIG_PPU_V1_H
#define CONFIG_PPU_V1_H

enum ppu_v1_static_element_idx {
    PPU_V1_ELEMENT_IDX_CORE0,
    PPU_V1_ELEMENT_IDX_CORE1,
    PPU_V1_ELEMENT_IDX_CORE2,
    PPU_V1_ELEMENT_IDX_CORE3,
    PPU_V1_ELEMENT_IDX_CORE4,
    PPU_V1_ELEMENT_IDX_CORE5,
    PPU_V1_ELEMENT_IDX_CORE6,
    PPU_V1_ELEMENT_IDX_CORE7,
    PPU_V1_ELEMENT_IDX_CLUSTER,
    PPU_V1_ELEMENT_IDX_DBGTOP,
    PPU_V1_ELEMENT_IDX_DPUTOP,
    PPU_V1_ELEMENT_IDX_GPUTOP,
    PPU_V1_ELEMENT_IDX_VPUTOP,
    PPU_V1_ELEMENT_IDX_SYS0,
    PPU_V1_ELEMENT_IDX_SYS1,
    PPU_V1_ELEMENT_IDX_COUNT,
};

#endif /* CONFIG_PPU_V1_H */
