#
# Arm SCP/MCP Software
# Copyright (c) 2018-2020, Arm Limited and Contributors. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

BS_LIB_NAME := SynQuacer PIK Clock Driver
BS_LIB_SOURCES := mod_synquacer_pik_clock.c

include $(BS_DIR)/lib.mk
